### PR TITLE
📜 quiz for level17

### PR DESCRIPTION
**Pull request by SabinaChita**
I have made a preliminary quiz for level 17, added for now only four questions. This PR is just to make sure I am on the right track but also if I am allowed to continue working on this. It took me a bit of time to figure out where I can find the quizzes and how I can write my tests, but now I'm on a roll.

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks @SabinaChita!

Best to finish the whole quiz before we merge it, so it wil be copied over to other languages as a whole. And maby @MarleenGilsing can take a look at the content quality next week?

**Comment by SabinaChita** [comment]
yes of course!

**Comment by SabinaChita** [comment]
Thank you @MarleenGilsing!

**Comment by SabinaChita** [comment]
I have finished the 10 questions for level 17. @MarleenGilsing  and @Felienne could you please take a look and check the content? I apologise for taking more than a week to get this done, I had several quarrels with the indentations in the programming env. but fortunately I won in the end.

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

Can you take a look at this Thursday? If you are happy, you may approve this!

**Comment by MarleenGilsing** [comment]
Hi Sabina, 

Great quiz. It was quite a hard one, for me too haha, but that's good for such a high level. I have got a couple of notes for you about the last questions:

Question 7 is too hard. We have never explained variable[0] (I myself didn't even know you could do that). 
Also we haven't used spaces between the variable and the [0]. 
Maybe it would be nice to use this one as one of the first questions and turn it into something easy like this: 

                     numbers = [43, 68 , 88, 23, 121]
                     max_num = numbers[5]
                     {print} 'The maximum number is ' max_num

Question 8 needs more indentation (4 spaces). And maybe change the first insects to insect, in `for insects in insects` , because we have never taught the kids that it's okay to use insects twice (again, i didn't know hahahha). This does mean changing the answer option as well. 

Question 9 mind the phrasing of the question: 'bellow' = 'below' and 'answer' = 'output'. 
Mind the indentation.  

Question 10 mind the indentation.
Answer option 2 is technically correct too, so you could make that one more obviously wrong. 
Answer option 3 is a bit confusing, maybe change it to: 'line 3 should be `volume_room = number * number * number`'

**Review by Felienne — DISMISSED** [review]
Changing status to keep an overview

**Comment by SabinaChita** [comment]
Hi @MarleenGilsing and @Felienne, silly me!! me and Marleen we talked about this on discord but I forgot to add comments here as well. Thank you @MarleenGilsing for your feedback!! I will include your feedback and have the changes ready to go!

**Comment by SabinaChita** [comment]
@MarleenGilsing and @Felienne: can you maybe help? In the quiz for level 17 all the answer options are showing on my local machine strange: the color of the answer B is gone and the line for answer A is gone. I do not know why this goes wrong, cannot find the code line that is connected to this so that i correct.
Screenshot 2023-12-19 at 11 33 16

**Comment by SabinaChita** [comment]
@Felienne great! thank you!!!! almost done with the last changes, made a new question instead of the old hard question 7, i will keep that one for level 18, haha.

**Comment by SabinaChita** [comment]
I have erased the difficult question number 7 and made a new question, i have added the suggestions for questions 8, 9 and 10 made by Marleen. Now the quiz seems finished. @Felienne and @MarleenGilsing  if you want to give the final okey that will be great!

**Comment by MarleenGilsing** [comment]
Looks good @SabinaChita! This one is ready to go!

**Comment by Felienne** [comment]
> Looks good @SabinaChita! This one is ready to go!

Great! I changed it to weblate-lock and I will merge weblate in, and then this one!

**Review by Felienne — APPROVED** [review]

**Pull request merged**
