### PR TITLE
[CHORE]  re-ordering tweak to yaml sorter (simplest solution)

### PR DESCRIPTION
**Pull request by yilmazdurmaz**
**Description**

The change is only on the "PREFERRED_KEY_ORDER" array so that the following keys are context-ordered.

quizzes: question_text and option-feedback (sub-keys)
slides: header-text-editor
pages: title-key-intro-levels (moves key and intro above levels)

**Fixes _issue or discussion number_**

It follows and slightly tweaks https://github.com/hedyorg/hedy/pull/4557
As suggested by https://github.com/hedyorg/hedy/pull/4557#issuecomment-1742169038

**How to test**

- Since this is a slight tweak to an already working sorter, it should pass automatic tests.
- sampled visual inspection on generated yaml files with git diff shows correct order

Merging will require Weblate lock, and generation of newly sorted files.

Please advise for further steps

**Checklist**
Done? Check if you have it all in place using this list: (mark with x if done)

- [ ] Contains one of the PR categories in the name
- [ ] Describes changes in the format above
- [ ] Links to an existing issue or discussion
- [ ] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Felienne** [comment]
This is one for @jtwaleson to look at I think

**Comment by jtwaleson** [comment]
@yilmazdurmaz I'm happy with the changes to the script, thank you! However, as the pages content has been updated, could you rebase the commit on main? Then we can merge.

**Comment by yilmazdurmaz** [comment]
@jtwaleson pre-commit CI is really fast to run and add its commit :) there are lots of changes on lots of translation files. I am yet to understand sync with Weblate, but I guess this needs a lock on it first, and many pushes and pulls.

**Comment by Felienne** [comment]
> @jtwaleson pre-commit CI is really fast to run and add its commit :) 

Yes a lot of progress was made there to make it all quicker!

> there are lots of changes on lots of translation files. I am yet to understand sync with Weblate, but I guess this needs a lock on it first, and many pushes and pulls.

I will merge #4602 first, lock Weblate and then merge this! Hope it will all go well

**Review by Felienne — APPROVED** [review]

**Pull request merged**
