### PR TITLE
📜 Workbook fixes, removes old structure

### PR DESCRIPTION
**Pull request by Felienne**
Removes the old workbooks and fixes a date type issue in nl

### CODE REVIEW

**Review by boryanagoncharenko — APPROVED** [review]

**Comment by Felienne** [comment]
Thanks for the approve Boryana, but I should have made this a draft since it still needs to be translated

**Comment by boryanagoncharenko** [comment]
> Thanks for the approve Boryana, but I should have made this a draft since it still needs to be translated

Oh no, I am very sorry. It did appear in my non-draft PR filter, so I reviewed it and even pushed a merge conflict resolving commit. Sorry, I hope this does not mess things up too much.

**Comment by Felienne** [comment]
> > Thanks for the approve Boryana, but I should have made this a draft since it still needs to be translated
> 
> Oh no, I am very sorry. It did appear in my non-draft PR filter, so I reviewed it and even pushed a merge conflict resolving commit. Sorry, I hope this does not mess things up too much.

No my bad! I should have made it draft!

**Comment by Felienne** [comment]
Ready for @MarleenGilsing to translate <3

**Comment by Felienne** [comment]
@boryanagoncharenko I removed the level 8 workbooks here so we can merge these fixes (should not have been one PR, sorry) will make a new PR with just level 8.

**Pull request merged**
