### PR TITLE
[FIX] Add warning back in

### LINKED ISSUE #4869: [BUG] InvalidSpaceWarning not being shown in the editor
**Describe the bug**

The editor is not showing the warning for `InvalidSpace` and maybe for other warnings that come from the server?:

image

### PR DESCRIPTION
**Pull request by Felienne**
Fixes #4869 

As far as I can see, @ToniSkulj removed this warning in #4320, I suspect by accident, but if not, let me know :) 

See:
image

**How to test**
Observe that code with a space at the start runs but also throws an error:

image

### CODE REVIEW

**Comment by Felienne** [comment]
Would be a good idea maybe to add a Cypress tests for this @jpelay?

**Review by jpelay — APPROVED** [review]
Thank you!! This was probably an oversight by us.

**Comment by Felienne** [comment]
> Thank you!! This was probably an oversight by us.

Np! Do we want to add an issue to make a test so we don't forget?

**Comment by jpelay** [comment]
> > Thank you!! This was probably an oversight by us.
> 
> Np! Do we want to add an issue to make a test so we don't forget?

Yeah, Im on it!

**Pull request merged**
