### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/Parsons](https://hosted.weblate.org/projects/hedy/parsons/)

* [Hedy/slides](https://hosted.weblate.org/projects/hedy/slides/)

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Cheatsheets](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

* [Hedy/Tutorials](https://hosted.weblate.org/projects/hedy/tutorials/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by yilmazdurmaz — COMMENTED** [review]
Hi, this is my first review ever. @Felienne  told me, through email, to correct these problems on Weblate if I got time.

I did so and at least these errors should now be gone. They were mostly coming from wrong/buggy  auto-translations, others were small typos.

I am not sure what is next, but my guess is to reject this PR, and let Weblate make a new one with the changes made in last 3-4 days. (and maybe manually commit them from Weblate)

Thanks

**Comment by Felienne** [comment]
> Hi, this is my first review ever. @Felienne told me, through email, to correct these problems on Weblate if I got time.
> 
> I did so and at least these errors should now be gone. They were mostly coming from wrong/buggy auto-translations, others were small typos.
> 
> I am not sure what is next, but my guess is to reject this PR, and let Weblate make a new one with the changes made in last 3-4 days. (and maybe manually commit them from Weblate)
> 
> Thanks

Thanks for the fixes! We don't have to close this PR, your changes are now added to it. We can see then if the tests are ready if everything is correct. If it is, we can close this and then the changes will go to alpha.

**Comment by yilmazdurmaz** [comment]
The order of commits Weblate sends are a bit odd for me; though there was a never edit, one commit had the older string in it for Spanish.

It took a few tries, but I am getting the hang of it and errors are almost over.

**Comment by yilmazdurmaz** [comment]
@Felienne  There is one annoying commit problem. although the string translation is alright on Weblate, when it commits it add 2 spaces on each line:
string: https://hosted.weblate.org/translate/hedy/adventures/es/?&offset=503
commit: https://github.com/hedyorg/hedy/pull/4511/commits/ba333d64d66b0cea31d71937b7c908a55ac480f1

also from the error message, it is as if it were taken as a program code and tried a compilation on it, `not valid Hedy code`:

> from adventure Calculadora
> in language es from level 13 gives error:
> The code you entered is not valid Hedy code. There is a mistake on line 5, at position 2. You typed a space, but that is not allowed. at line (5, 2)

Right now, there is only this error preventing the merge. Can you please check what is going on with this string and/or its commit.

**Comment by Felienne** [comment]
> @Felienne There is one annoying commit problem. although the string translation is alright on Weblate, when it commits it add 2 spaces on each line: string: https://hosted.weblate.org/translate/hedy/adventures/es/?&offset=503 commit: [ba333d6](https://github.com/hedyorg/hedy/commit/ba333d64d66b0cea31d71937b7c908a55ac480f1)
> 
> also from the error message, it is as if it were taken as a program code and tried a compilation on it, `not valid Hedy code`:
> 
> > from adventure Calculadora
> > in language es from level 13 gives error:
> > The code you entered is not valid Hedy code. There is a mistake on line 5, at position 2. You typed a space, but that is not allowed. at line (5, 2)
> 
> Right now, there is only this error preventing the merge. Can you please check what is going on with this string and/or its commit.

Yes, this is an annoying issue that has to do with indentation settings. Thank you for the hard work on this, it really matters a lot to us! I think we are now good to go.

**Review by Felienne — APPROVED** [review]
Yes, unit tests are passing, let's go!

**Comment by yilmazdurmaz** [comment]
> Yes, this is an annoying issue that has to do with indentation settings.

@Felienne , your fixing commit is a good example where else to look.

Many other files for other languages has still this same indentation including the source, they are just not yet surfaced because of auto-translation.

If not handled by others, I know where I may help after finishing the quizzes for Turkish.

**Comment by Felienne** [comment]
> If not handled by others, I know where I may help after finishing the quizzes for Turkish.

Thanks for the kind offer! We will be looking for an automated solution for now, hopefully we can find that.

**Pull request merged**
