### PR TITLE
💻 Front page start learning/teaching

### LINKED ISSUE #4655: [UI idea] Replace "try it" button on the front-page
The front-page now has a "try out" button, but that leads right to the programming interface. It is a bit of very old legacy, when we thought we were designing a tool for kids. Since we are now clearly designing a tool for teachers, this button is not productive anymore. I'd like the front page to have two buttons, a bit like the sign-up page has also (not this layout, but this choice):

image

So maybe a "start programming" and "start teaching" button? Start programming than works as it does now, and start teaching will lead to hedy.org/start (which is now still a bit messy but Sabina is working on that)

### PR DESCRIPTION
**Pull request by Annelein**
Fixes #4655 
Depends-On: #5156

Screenshot 2024-03-01 at 11 31 37

Start teaching goes to:
- if not logged in: `signup?teacher=true`
- if logged in as teacher: `for-teachers`
- if logged in as student: `my-profile`

In the future, we want it to be linked to #5183

### CODE REVIEW

**Comment by Annelein** [comment]
@hasan-sh you can review this?

**Comment by Felienne** [comment]
Hi @Annelein!

How you are seeing some snow there!

Can you fix the conflicts and the tests?

image

Thanks!

**Comment by Felienne** [comment]
(it looks great, so if @hasan-sh is ok with the code, we can merge and deploy this!)

**Comment by Annelein** [comment]
> Hi @Annelein!
> 
> 
> 
> How you are seeing some snow there!
> 
> 
> 
> Can you fix the conflicts and the tests?
> 
> 
> 
> image
> 
> 
> 
> Thanks!
> 
> 



Snow is great!! All my open PR's are depending on #5156 , those translations are made in that PR.... So waiting for it to be merged, I asked @hasan-sh many times or for a workaround

**Comment by hasan-sh** [comment]
> > Hi @Annelein!
> > How you are seeing some snow there!
> > Can you fix the conflicts and the tests?
> > image
> > Thanks!
> 
> Snow is great!! All my open PR's are depending on #5156 , those translations are made in that PR.... So waiting for it to be merged, I asked @hasan-sh many times or for a workaround

I think @jpelay is going to review that PR asap, so should be solved. But you could always just copy the translation keys from that pr!!

**Review by hasan-sh — APPROVED** [review]
All good!

**Pull request merged**
