### PR TITLE
[FIX] Added brackets around keywords for languages bg, bn, cs, de, el, fy, id, it, and sw

### PR DESCRIPTION
**Pull request by ana3999**
**Description**

Added brackets to the keywords.

**Fixes _issue or discussion number_**

Addresses https://github.com/hedyorg/hedy/issues/3537 for bg, bn, cs, de, el, fy, id, it, and sw.

**How to test**

Users can check that they can now see that the keywords that are surrounded by brackets are now translated into the appropriate language.

**Checklist**
Done? Check if you have it all in place using this list:*
  
- [X] Contains one of the PR categories in the name
- [X] Describes changes in the format above
- [X] Links to an existing issue or discussion 
- [X] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Felienne** [comment]
This one has an issue in cs.yaml: 

image

**Comment by Felienne** [comment]
Hi @ana3999! 

Because weblate was merged, issues have arisen here, the sad reality of a large open source project! Can you redo your changes? de is already fixed in #3745

**Comment by Felienne** [comment]
Hi @ana3999, do you plan to fix the issues in this PR? If not, we will close it later this week because the conflicts are now getting to large for us to fix.

**Review by Felienne — DISMISSED** [review]
Conflicts need to be fixed

**Comment by ana3999** [comment]
Hi Felienne! I apologize for the confusion-I think I mixed up what was happening with the merged branch and this branch. I can get these conflicts fixed by tomorrow!

**Comment by Felienne** [comment]
I really tried but this Pr is too far behind to sensibly merge.

**Pull request closed without merging**
