### PR TITLE
[UI] Improve public adventures

### LINKED ISSUE #4909: [UI idea] Improvements for public adventures
Now that the public adventures are live and I had a chance to play with them, I have a few requests for improvement. We can of course split this into separate issues where needed!

### Update text above adventures
We recently added info text above the adventures, let's also explain public adventures there, with a link to the (yet to be written) teacher manual part about it.
image

### Change teacher into author?
I am not really sure what the "teacher" column indicates, but I think it means author? An interesting question is if we want to keep the original author there or the author that cloned the adventure? I would lean towards (also?) showing the original author just so it is more clear what is what.

image

## Show this is a dropdown
I first did not understand this was a dropdown (it misses the arrow down icon). 
image

Of course that has to do with the lack of a general guideline for design of elements, but maybe this is a good moment to centralize the dropdown elements? In other places it does look like a dropdown, f.e. in customization:
image

## Make tags multiselect
This I think maybe should not be a dropdown, because people might want to search for multiple tags (age and theme, for example) 
image
 
## Real preview for preview
Once @jtwaleson is ready with #4822, we can link to a preview in the Hedy UI rather than the edit UI, that would be a lot nicer I think!

## Show a bit more info
A tile now only shows the title and some meta data, but there is some room in the tiles. Could we add maybe the first text line of the adventure, to give a better sense of what it is about?
image

### PR DESCRIPTION
**Pull request by hasan-sh**
Fixes #4909 
This PR improves the public adventures page, as described by felienne in the aforementioned issue. It also introduces some new things. Here's a list of things done:
- [x] Change "Teacher" column name to "Author" of an adventure.
   - Now we distinguish between the author and owner. E.g., if a you clone an adventure, you'd be the owner, but not the author. 
- [x] Dropdown indication
- [x] Tags multi-select dropdown
- [x] Preview mode for any (public) adventure 
   - clicking on the preview icon, takes the user to the code-level page where they can run their code for an adventure and explore what it encapsulates in different levels.

### CODE REVIEW

**Comment by Felienne** [comment]
> * More info in adventure cards.
>   
>   * [x]  language
>   * [x]  author
>   * [ ]  code?? (while undoubtedly compelling, introduces a degree of visual complexity that, regrettably, renders the card somewhat crowded, lessening its inherent elegance and simplicity.)

I think we can remove this from the PR text since we are not planning to move the cards forward? Just to make it easier later on for us to understand the PR if we ever need to read back?

**Comment by Felienne** [comment]
I get a Keyerror if I try this locally for Teacher1:

image

```
[2024-01-05 13:45:42,165] _internal.py _log 96 <INFO>: 127.0.0.1 - - [05/Jan/2024 13:45:42] "GET /public-adventures HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/felienne/Documents/GitHub/hedy/website/auth.py", line 269, in inner
    return f(*args, user=current_user(), **kws)
  File "/Users/felienne/Documents/GitHub/hedy/website/public_adventures.py", line 57, in index
    return render_template(
  File "/Users/felienne/Documents/GitHub/hedy/website/querylog.py", line 196, in wrapped
    return fn(*args, **kwargs)
  File "/Users/felienne/Documents/GitHub/hedy/website/flask_helpers.py", line 13, in render_template
    return flask.render_template(filename, **kwargs)
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/felienne/Documents/GitHub/hedy/templates/public-adventures.html", line 2, in top-level template code
    {% extends "auth.html" %}
  File "/Users/felienne/Documents/GitHub/hedy/templates/auth.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/Users/felienne/Documents/GitHub/hedy/templates/layout.html", line 87, in top-level template code
    {% block full_width_content %}{% endblock %}
  File "/Users/felienne/Documents/GitHub/hedy/templates/auth.html", line 17, in block 'full_width_content'
    {% block regular_content %}{% endblock %}
  File "/Users/felienne/Documents/GitHub/hedy/templates/public-adventures.html", line 62, in block 'regular_content'
    {{ render_partial('htmx-adventure-card.html', user=user, adventure=adventure) }}
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/jinja_partials/__init__.py", line 51, in render_partial
    return Markup(renderer(template_name, **data))
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/felienne/Documents/GitHub/hedy/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/felienne/Documents/GitHub/hedy/templates/htmx-adventure-card.html", line 32, in top-level template code
    <p class="text-gray-600 mt-1">{{_('language')}}: {{ lang_to_sym(adventure.language) }}</p>
  File "/Users/felienne/Documents/GitHub/hedy/app.py", line 2295, in lang_to_sym
    return ALL_LANGUAGES[lang]
KeyError: ''
```

**Comment by hasan-sh** [comment]
> I get a Keyerror if I try this locally for Teacher1:

Should be fixed now @Felienne!

**Comment by Felienne** [comment]
The KeyError seems fixed but now I have issues in previewing, this one for adventures that I have cloned:

image

and this when I have not cloned:

image

**Comment by Felienne** [comment]
All seems to work now!!

image

If you update the PR description to be more readable, we can merge this!

**Comment by hasan-sh** [comment]
> If you update the PR description to be more readable, we can merge this!

Great, once this is merged, i will start on the utilizing the cards then looking into what we discussed (trying to show dynamic tabs code within public adventrues.)

**Review by Felienne — APPROVED** [review]
Good to go!

**Pull request merged**
