### PR TITLE
[CHORE] Script to sort all yaml files in the content dir

### LINKED ISSUE #4541: [CONTENT] Sort all yamls
Text from #4484

Another thing that complicates adding new content or changes to (partly) translated files is that each file uses a different order of headings. For example: In English all the quizzes go from question 1 to 10, but some other files can go 1,5,3,2,8,9,10,7,6,4. In quizzes, this is not really a problem because you can still see the number so you know which heading this is. But in the teacher manual, all the headers are translated so you can't easily see which header is which. That makes it hard to make changes to the content. 

This same issue causes an issue in /slides (see #4480) now where the order is messed up and accidentally meaningful. So we should sort all yamls, not just the toplevel, but sublevels too. 

Maybe this can be done as a setting in Weblate? Or maybe we can run a script to do it once, because I think Weblate do keeps the same order. If we do it with a script in the repo (f.e. at build) we should test whether that does not mess up weblate.

### PR DESCRIPTION
**Pull request by jtwaleson**
**Description**

Adds a script to rewrite the yaml files in the content directory deterministically. Like we do with python code using autopep8 but for the translation texts.

Fixes #4541 

**How to test**

- Enable the script in .pre-commit-config.json  and run `pre-commit run --all`.
- Check if unit tests succeed by running them locally on the rewritten yaml files
- Verify if indented parsons still work by going to level 8 -> puzzle and seeing that `print 'You are selected in team... '` is indented.

**Checklist**
Done? Check if you have it all in place using this list: (mark with x if done)

- [x] Contains one of the PR categories in the name
- [x] Describes changes in the format above
- [x] Links to an existing issue or discussion
- [x] Has a "How to test" section

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks for the progress @jtwaleson! Maybe we can leave the changed yamls outside of the PR for now, so it does not cause conflicts all the time. 

A good workflow could be:

1. create a PR with the new script in it but no changes to yamls yet
2. merge all weblate PRs and content PRs
3. close weblate for maintenance (I can do that) 
4. enable the script, run it, generate a new PR with updated yamls
5. re-open weblate

Let me know what you think! You can also leave the yamls in, then I can also make this PR up to date with main, and then I can also do steps 2 to 5 instead.

**Comment by jtwaleson** [comment]
Yes that works, I'll get it ready. But: the unit tests were failing. I think it's due to stripping whitespace (space & newlines)  from the start/end of some strings in the yaml files that might be meaningful. @Felienne Could you take a look and see if we should maybe preserve the whitespace or update the tests? I dont have enough context to make that call. https://github.com/hedyorg/hedy/actions/runs/6317607832/job/17154763229

When in doubt I'll remove the `strip` from the script and see if the tests pass.

**Comment by Felienne** [comment]
> Yes that works, I'll get it ready.

Great!

>  But: the unit tests were failing. I think it's due to stripping whitespace (space & newlines) from the start/end of some strings in the yaml files that might be meaningful. @Felienne Could you take a look and see if we should maybe preserve the whitespace or update the tests? I dont have enough context to make that call. https://github.com/hedyorg/hedy/actions/runs/6317607832/job/17154763229
> 
> When in doubt I'll remove the `strip` from the script and see if the tests pass.

Hmmm that does not look like a familiar issue to me, shall we try without the strip first? If that doesn't help I can dive in.

**Comment by jtwaleson** [comment]
Ah I figured it out. The content/adventures directory is used for testing. I modified the script to leave the whitespace alone for that directory. I will send a final PR tomorrow morning.

**Comment by yilmazdurmaz** [comment]
> I think it's due to stripping whitespace (space & newlines) from the start/end of some strings in the yaml files that might be meaningful.

If this is about "code" sections, then at least "content/parsons" and teacher manual's "common mistakes" (part of content/webpages) has code sections. parsons codes are complete programs, others are mostly runnable upon copy-paste.

**Comment by jtwaleson** [comment]
> > I think it's due to stripping whitespace (space & newlines) from the start/end of some strings in the yaml files that might be meaningful.
> 
> If this is about "code" sections, then at least "content/parsons" and teacher manual's "common mistakes" (part of content/webpages) has code sections. parsons codes are complete programs, others are mostly runnable upon copy-paste.

Alright, thanks. I've confirmed that the unit tests still pass if only the "adventures" are not stripped. I think specifically the unit tests take the `story_text` and `example_code` fields from the adventures.

For the parsons/website parts: do you foresee a problem if leading/trailing whitespace is removed? I don't think it will affect anything or the ability to copy paste, but I'm pretty new to the project.

**Comment by yilmazdurmaz** [comment]
I am too new for about 3 weeks. I may later join in for coding. But for now, I am contributing to translations and I am close to finish them all. And this gave me some insight about the content and their ordering for us translators. I don't have yet the mindset to understand your sorting code or how Hedy processes them, but I have some concerns to share other than whitespaces.

Current content of yaml files have mostly-correct positions that follows the flow of text. I use the "position" ordering while translating, so the next string to be translated follows what I have just translated. I tried to sort by "keys" but this sorts keys themselves with alphabetical order, and if items don't use numbers, their order does not make any sense, and translations becomes soulless as the context becomes scrambled. other sort modes behaves the similar. This actually won't be much of a problem for 90+% converted languages, but there are many of them below 50% translated.

ordering with "content", and their positions becomes much crucial. I had checked some of your first "sorted" files and they lack this important factor. Below are current orders for most of them. there are some ordering sync issues among language files (slide pages for example), and a sorting from english-template is the main thing they need.

in achievements, each achievement goes from first to get "well_begun_is_half_done" and goes to last to get "hedy_certificate". not in alphabetical order. There is no alphabetical order, and some won't make sense with this order in the file, but translators may find it easy to follow (I did). This can be reordered by the meaning, but alphabetical sort will make it harder in my opinion.

in quizzes, question and its code comes, first then answers and their hints, then question hint. answers depend on what we put into the question so it and the code should come first. also answers mostly use what is printed on the question itself. question hints might come 3rd but not as important as others. The current order of appearance is great for translators. (some quiz levels and some questions are out of order now)

in parsons, first comes a question-like story about the code, and 4-5 code lines that make a runnable-program when sorted. the story makes better sense to come first, then the code lines. this affects what translations to put into the code. by the way, check how these codes are used and about removing the whitespaces; I think Hedy takes this code and tries to run it. Then indentation matters, so whitespaces for them too.

adventures are most sensitive to this "content" order. currently they start from the very first chapter and ends with last level adventure. first a welcome page for a level, then new commands comes, then other adventures. your sorted file completely changed this order, thus translator suffer much if you let them slip.

slides are actually the easiet I guess. they already have two main yaml levels both marked with numbers, for levels and for pages. in 3rd level however, they have header-text order. your sort, interestingly, reversed this to text-header order. (personally, I would appreciate if you could sorted them first :D )

cheatsheets are simple as they have level numbers, and only 3-component items in them, but each item has an order of "name-explanation-code. translators will benefit when they see these with this order.

pages are a mix of different component throughout the whole Hedy pages, for that they actually do not have a real overall structure, but each page contained have an order. from your ordered files, I actually see a problem only on "common mistakes" parts. you will see "error text/code, then solution text/code" order. translating in this order keeps the continuity. your sorted files have reversed it to "code/text" order, which makes it a bit odd if you in that order.

This took long, but it gives why hearing "the sorting" gives me shivers :) There are projects this order means nothing. but here they mean a lot, if not everything. I may join forces later when I finish my translations (quizzes, they are easy but many).

**Comment by yilmazdurmaz** [comment]
I am also new for about 3 weeks now. I may later join in for coding. But for now, I am contributing to translations and I am close to finishing them. And this gave me some insight into the content and their ordering for us translators. I don't have yet the mindset to understand your sorting code, but I have some concerns to share.

Current content of yaml files have mostly-correct positions that follow the flow of text. on Weblate, I use the "position" ordering while translating, so the next string to be translated follows what I have just translated. I tried to sort by "keys" but this sorts keys themselves with alphabetical order, and if items don't use numbers, then they get scrambled and translations becomes soulless. other sort modes behave similarly. This ordering is not much of an issue for 90+% translated languages but there are many below 50% and less.

ordering with "content", and their positions becomes much crucial. I had checked some of your first "sorted" files and they lack this important factor. Below are current orders for the most important ones. there are some ordering sync issues among language files (slide pages for example), and a sorting from English-template is the main thing they need.

I may join forces later when I finish my translations. Quizzes take most of my time. They are easy, but there are many.

**Comment by Felienne** [comment]
> I am too new for about 3 weeks. I may later join in for coding. But for now, I am contributing to translations and I am close to finish them all. And this gave me some insight about the content and their ordering for us translators. I don't have yet the mindset to understand your sorting code or how Hedy processes them, but I have some concerns to share other than whitespaces.
> 
> Current content of yaml files have mostly-correct positions that follows the flow of text. I use the "position" ordering while translating, so the next string to be translated follows what I have just translated. I tried to sort by "keys" but this sorts keys themselves with alphabetical order, and if items don't use numbers, their order does not make any sense, and translations becomes soulless as the context becomes scrambled. other sort modes behaves the similar. This actually won't be much of a problem for 90+% converted languages, but there are many of them below 50% translated.
> 
> ordering with "content", and their positions becomes much crucial. I had checked some of your first "sorted" files and they lack this important factor. Below are current orders for most of them. there are some ordering sync issues among language files (slide pages for example), and a sorting from english-template is the main thing they need.
> 
> in achievements, each achievement goes from first to get "well_begun_is_half_done" and goes to last to get "hedy_certificate". not in alphabetical order. There is no alphabetical order, and some won't make sense with this order in the file, but translators may find it easy to follow (I did). This can be reordered by the meaning, but alphabetical sort will make it harder in my opinion.
> 
> in quizzes, question and its code comes, first then answers and their hints, then question hint. answers depend on what we put into the question so it and the code should come first. also answers mostly use what is printed on the question itself. question hints might come 3rd but not as important as others. The current order of appearance is great for translators. (some quiz levels and some questions are out of order now)
> 
> in parsons, first comes a question-like story about the code, and 4-5 code lines that make a runnable-program when sorted. the story makes better sense to come first, then the code lines. this affects what translations to put into the code. by the way, check how these codes are used and about removing the whitespaces; I think Hedy takes this code and tries to run it. Then indentation matters, so whitespaces for them too.
> 
> adventures are most sensitive to this "content" order. currently they start from the very first chapter and ends with last level adventure. first a welcome page for a level, then new commands comes, then other adventures. your sorted file completely changed this order, thus translator suffer much if you let them slip.
> 
> slides are actually the easiet I guess. they already have two main yaml levels both marked with numbers, for levels and for pages. in 3rd level however, they have header-text order. your sort, interestingly, reversed this to text-header order. (personally, I would appreciate if you could sorted them first :D )
> 
> cheatsheets are simple as they have level numbers, and only 3-component items in them, but each item has an order of "name-explanation-code. translators will benefit when they see these with this order.
> 
> pages are a mix of different component throughout the whole Hedy pages, for that they actually do not have a real overall structure, but each page contained have an order. from your ordered files, I actually see a problem only on "common mistakes" parts. you will see "error text/code, then solution text/code" order. translating in this order keeps the continuity. your sorted files have reversed it to "code/text" order, which makes it a bit odd if you in that order.
> 
> This took long, but it gives why hearing "the sorting" gives me shivers :) There are projects this order means nothing. but here they mean a lot, if not everything. I may join forces later when I finish my translations (quizzes, they are easy but many).

Thanks for all the detailed info @yilmazdurmaz! We are looking onto sorting with a custom order that is a bit more logical for translators at the moment. We will let you know if we have a new draft.

**Comment by jtwaleson** [comment]
@mennoliefstingh I made the pre-commit hook a bit more generic by just invoking all the pre-commit checks in a github action, rather than individual checks. This way the CI/CD checks are identical to the local checks. Do we then still need the separate pre-commit.ci integration?

**Comment by jtwaleson** [comment]
@yilmazdurmaz I took your comments into account and in the script you can see the order which makes sense for 99% of the cases. For the parsons: good catch, I didn't think of that. Luckily it still works, as the parsons have the entire snippet in one string, not line by line. The `strip` function only removes the whitespace at the start and end of the entire string.

**Comment by jtwaleson** [comment]
> Thanks for the progress @jtwaleson! Maybe we can leave the changed yamls outside of the PR for now, so it does not cause conflicts all the time.
> 
> A good workflow could be:
> 
> 1. create a PR with the new script in it but no changes to yamls yet
> 2. merge all weblate PRs and content PRs
> 3. close weblate for maintenance (I can do that)
> 4. enable the script, run it, generate a new PR with updated yamls
> 5. re-open weblate
> 
> Let me know what you think! You can also leave the yamls in, then I can also make this PR up to date with main, and then I can also do steps 2 to 5 instead.

Ok @Felienne , 1 is done and ready for final review. Unfortunately 2-5 are the the most work I guess...

**Review by Felienne — DISMISSED** [review]
Hi @jtwaleson!

I am not sure I understand these changes in the context of this PR, are they needed? If so, can we document their role?

Thanks!

**Comment by jtwaleson** [comment]
> Hi @jtwaleson!
> 
> I am not sure I understand these changes in the context of this PR, are they needed? If so, can we document their role?
> 
> Thanks!

Good point, I added documentation to the intro of the `.github/workflows/pre-commit.yml` file. Let me know if that clears up what it does.

The reason that it's relevant here is that I wanted to deliver a complete solution, so not just the script, but also integrate it in the CI/CD config so that it's done automatically. As we first have to do some cleanup with open PRs for the content directory (steps 2-5 in your comment above), we can not have the CI/CD enabled right now, or it would lead to many merge conflicts which first need to be incorporated. However, once that is done, all we need to do to activate checking both locally and in CI is uncomment the yaml rewriter in `.pre-commit-config.json`.

Note that after this change we will have two `pre-commit` checks on the main repo. One via this workflow and one via the external `pre-commit.ci` integration. The reason for adding the `pre-commit` work is that the `pre-commit.ci` does not work in forks. As cautious contributors want to ensure that everything checks out BEFORE opening a PR and taking attention from maintainers, it's preferred if all the checks work on forks too.

**Comment by yilmazdurmaz** [comment]
> as the parsons have the entire snippet in one string, not line by line

about this "one string", please check if you have the correct view of yaml files.

some files have the text in a single string (slides, adventures) ("\n" for new lines):
````
text: "The final text code that you can use in level 1 is `{echo}`.\n\n`{echo}` is used to repeat the answer of an `{ask}`.\n"

start_code: "{print} hello world!"
````
while others uses a pipe and then indented block (parsons, adventures) (I hope there is no non-pipe version of this):
````
start_code: |-
    name = 'Hedy'
    {print}('My name is ', name)

example_code: |
    ```
    age = {ask} 'How old are you?'
    {if} age > 12
        {print} 'You are older than I am!'
    ```
````

**Comment by Felienne** [comment]
I will take a look at this later on (tomorrow I will not be online all day), but I just want to make sure @jtwaleson has seen @yilmazdurmaz's comment about the one line strings looking different?

**Comment by yilmazdurmaz** [comment]
just came to my mind: how are the translated code strings seen, saved and treated for right-to-left languages? I checked for Arabic and Hebrew. translators seem to write codes left-to-right order, same as above. but "what if" they also reverse them too, and maybe they already did (I don't know if the code would work that way though). Trimming extra spaces at the end might then break the indentation of the last code line.

Let's keep in mind that extra steps and tests might be needed for such languages.

**Comment by yilmazdurmaz** [comment]
About my last statement for RTL languages. it seems they are stored in reverse order (LTR) in yaml files, though used as RTL in adventure pages and on Weblate. This is one such example code:
https://github.com/hedyorg/hedy/blob/77a2b4c40c065ec45e29fa084fd037cdd857660e/content/adventures/he.yaml#L149

I hope this is a feature from Weblate and true for all such strings. Let this be a reminder for a check.

**Comment by jtwaleson** [comment]
Thanks for being so cautious here @yilmazdurmaz !

I made the changes on a separate branch (first applying the script with disabled "strip" function and then another commit that runs it as normal). Please see the commit that applies strip here: https://github.com/jtwaleson/hedy/commit/fe6c9ddaf23ef61f90eda30ba7e2bfb8ca539bea

Re: multiline handling -> Multiline strings in yaml are read into python as one string. Only at the beginning and end of that string is whitespace stripped. I believe we are good here.

Re: RTL languages and lines written LTR -> This is a very valid concern!

Looking at the diff, these are my conclusions:
1) This is a change we want because it cleans up a lot (if people disagree and we actually don't care about the whitespace cleanup, we can also choose to disable strip in the script, fine by me!).
2) There are no relevant code changes in the RTL languages (I checked "ar", "fa", "he", "pa_PK", "ur"). I'm not able to read the languages, but am quite sure the scenario you sketched above did not occur.

So: I think we are good to go with the script!

I'd appreciate if you could check the diff and see if you support my conclusions :)

**Comment by yilmazdurmaz** [comment]
I peeked at the arabic files as this language seemingly higher translation rate (albeit many strings not actually translated) so that I could see more translated code parts. Seems codes are stored im yaml as LTR and use RTL on Weblate and on Hedy.

That is nice. I think we can say most is done already. @jtwaleson  Great work!

For the moment, there are two things I can add:
- I noticed you added a PREFERRED_KEY_ORDER to the script. have you changed something before you applied on yaml files? that you forgot to commit? if not, please check why this happened:
  - for quizzes, it has this order "question_text" and then "code"
  - but resulting files have these two in reverse order. remaining key seems fine
- how deep can you keep preferred orders?
  - for quizzes, for example, "mp_choice_options" is an array but each option in it has its own sub keys
  - "option" and then "feedback". this order also helped me a lot while translating.
  - sorter changes this order as "f" comes before "o".

**Comment by Felienne** [comment]
Ok, @jtwaleson, I am testing the script, and it seems to all go well, so data points:

Parsons remain indented:

image

Story_text comes before code:
image

Slides go in order:
image

**Review by Felienne — APPROVED** [review]
Wow, this worked! 

🥳 

Thanks for the hard work @jtwaleson and for all feedback @yilmazdurmaz!

**Comment by jtwaleson** [comment]
Great!

@yilmazdurmaz for your last comments, I think we chose for "progress rather than perfection". Now that the bulk of the work is done we can finetune the script a bit further if you think it's universally better for the translators. You can experiment with this on a fork and running the `pre-commit run --all` command after making changes to the script. Let me know if that works.

> I peeked at the arabic files as this language seemingly higher translation rate (albeit many strings not actually translated) so that I could see more translated code parts. Seems codes are stored in yaml as LTR and used RTL on Weblate and on Hedy.
> 
> That is nice. I think we can say most is done already. @jtwaleson Great work!
> 
> For the moment, there are two things I can add:
> 
> * I noticed you added a PREFERRED_KEY_ORDER to the script. have you changed something before you applied on yaml files? that you forgot to commit? if not, please check why this happened:
>   
>   * for quizzes, it has this order "question_text" and then "code"
>   * but resulting files have these two in reverse order. remaining key seems fine
> * how deep can you keep preferred orders?
>   
>   * for quizzes, for example, "mp_choice_options" is an array but each option in it has its own sub keys
>   * "option" and then "feedback". this order also helped me a lot while translating.
>   * sorter changes this order as "f" comes before "o".

**Comment by yilmazdurmaz** [comment]
> I think we chose for "progress rather than perfection".

@Felienne  @jtwaleson I must object to this idea when it comes to user-facing parts of the project.
Although you have hedy-alpha, if we are not notified early enough many problems can easily go into production Hedy, and when we noticed problems weeks might have passed and recovering from damage might go harder. 

Anyways, considering many languages are currently in mayhem as most have wrong strings already, I think this has gone for the better for them.

In any case, for the moment, let me report current problems on a few parts of the sorted files and how Weblate see them:
- for the moment, only "webpages" component seems affected. there 24 "needs editing" string.
  - upon checking "content/pages/tr.yaml" file, at least "home-sections" and "join-sections" we scrambled
  - "Supporting Hedy" item from "join section" went into "home-section".
  - I noticed this after re-translating half of them. now there are 11 left.
- This problem seems not issue since I am around, but could happen when translators were not around this frequently.
- Weblate sees these source changes as "need checks" on the overview page and mostly as "failing checks" inside the component.
  - there was no "needs editing" and this is a big issue
  -  if somehow a translation got no error even after scrambled, then it is hard to know without checking all previously translated content.

For the moment, can you please check how strings from different content levels got scrambled, at least "home-sections" and "join-sections".

**Comment by yilmazdurmaz** [comment]
> For the moment, can you please check how strings from different content levels got scrambled, at least "home-sections" and "join-sections".

I have found the cause: commit 6538250 in #4522 that came right before the sorting. Too bad I couldn't notice it coming as it proves the sorter is working perfect. 

We shall look at the Weblate's behaviour though, if it misses anything when changes are made in the source.

Then we have only 1 key order issue in quizzes and few sub-key sorting issues in other components, purely for us translators to stay in context. I think this order issue comes in this line:
```
    # parsons
    "story",
    "code",
    # quizzes
    "question_text",
    "code",
    "output",
    ....
```
keys for "parsons" also has the same name "code" which comes before "question_text".  without changing one or both names to like "parson_code" and "quiz_code", we may add a check for the file name, or change the "preferred keys" to hold actual component name.

@jtwaleson You may work on it while you are still burning hot :) And thanks again for this nice tool.

**Comment by Felienne** [comment]
> > For the moment, can you please check how strings from different content levels got scrambled, at least "home-sections" and "join-sections".

> I have found the cause: commit [6538250](https://github.com/hedyorg/hedy/commit/653825094c2e1db7d5afce2cfd75afd0fefb4c8b) in #4522 that came right before the sorting. Too bad I couldn't notice it coming as it proves the sorter is working perfect.

Yes, sorry, I had to merge the /start PR before merging the sorter, since otherwise it would go outdated, sadly reverting a few of the changes you made. 

> Then we have only 1 key order issue in quizzes and few sub-key sorting issues in other components, purely for us translators to stay in context. I think this order issue comes in this line:
> 
> ```
>     # parsons
>     "story",
>     "code",
>     # quizzes
>     "question_text",
>     "code",
>     "output",
>     ....
> ```
> 
> keys for "parsons" also has the same name "code" which comes before "question_text". without changing one or both names to like "parson_code" and "quiz_code", we may add a check for the file name, or change the "preferred keys" to hold actual component name.
> 
> @jtwaleson You may work on it while you are still burning hot :) And thanks again for this nice tool.

If you have not done so already, feel free to make an issue about this, or maybe even make a PR that adds this sorting. But know it is surely a nice to have, but we have a few other things on our minds at the moment, so likely ik will take a while.

**Pull request merged**
