### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/Parsons](https://hosted.weblate.org/projects/hedy/parsons/)

* [Hedy/slides](https://hosted.weblate.org/projects/hedy/slides/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

* [Hedy/Cheatsheets](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

* [Hedy/Tutorials](https://hosted.weblate.org/projects/hedy/tutorials/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by yilmazdurmaz** [comment]
A lot of "2 spaces" and "comma" problems. I will try correcting them on Weblate. Some might need a touch on source yaml files for spaces.

**Comment by Felienne** [comment]
Thanks for the fix @yilmazdurmaz! But I would not spend too much time on it now, because this will be soon fixed by the yaml-prettifier. I will try to merge that tomorrow or Monday.

**Comment by yilmazdurmaz** [comment]
some of these, like "2 spaces", will need that prettifier like you said. Others are mainly translator typos in runnable codes. Does the prettifier also handle such issues?

I have finished Turkish translations and, as you may guess, I would like to see them in action before diving into possible corrections. The errors here will delay this so I may at least reduce them for the moment. And if the remaining are only spacing errors, you can make a merge without waiting for the completion of prettifier.

As I am using Weblate over 3 month now, I learned to find strings and fast switch between languages for particular stings. So handling these errors won't be much of an issue for me.

**Comment by yilmazdurmaz** [comment]
:( It is unfortunate they all seem to be about 2-spaces. Many are not-updated old string and maybe half are not even translated. I think they surfaced now here because someone actually made changes elsewhere and the file has found the chance to be tested.

@Felienne I now fully leave the issue to your hands

**Pull request merged**
