### PR TITLE
🖊️💻 Syntax highlighting for variables

### LINKED ISSUE #4853: [UI idea] Highlight variables
One feature that could really help students is the highlighting of variables. Now that we've merged CodeMirror in, we can start working on this.

When I was first starting to work on the CodeMirror grammars, I wanted to parse variables directly on the grammars, but at the first few levels we really have no way to distinguish between text and variables. The way to move this forward then, is by using the Tree lezer generates and iterating trhough it.

### PR DESCRIPTION
**Pull request by jpelay**
Adds syntax highlighting for variables in both read only and main editors. It works by checking for variables definition in `is`,`ask`, etc and then highlighting the places where those names appear in the program. This is done in every update of the document, but since the size of our programs is small, this doesn't cause such a big overhead.

Fixes #4853 

**How to test**

Follow these steps to verify this PR works as intended:

* Go to the Hedy page and see that the variables are highlighted

### CODE REVIEW

**Comment by Felienne** [comment]
Owwwww looking great!!

image

**Comment by Felienne** [comment]
Let me know when it is ready to be merged!

**Comment by jpelay** [comment]
> Let me know when it is ready to be merged!

These are the things that I want to do before merging this:

* Different color for function names.
* Scope the variables that are inside a function, so variables defined inside them won't be colored in the main program.

And I'd like to discuss the following before continuing:

* Change the yellow color of the variables, since, as you said it can be a bit overwhelming in higher levels when
* Annelise suggested that we change the color of text in the earlier levels to also be purple, like the one enclosed in quotes. What do you think?

**Comment by jpelay** [comment]
Hi, @Felienne! This is ready for review 😄 I changed the colors to be subtler. 

image

**Comment by Felienne** [comment]
Love it!!!!

image


> * Annelise suggested that we change the color of text in the earlier levels to also be purple, like the one enclosed in quotes. What do you think?

I think she is right, it should be the same color (not sure purple is the right color to be honest!) Shall we make an issue for that?

**Review by Felienne — APPROVED** [review]

**Pull request merged**
