### PR TITLE
[CONTENT] Split keywords into adventures

### PR DESCRIPTION
**Pull request by MarleenGilsing**
Splits new keywords into separate adventures allowing for a better flow in the learning trajectory, f.e. in level 2 is, ask and sleep get their own tabs:

image

### CODE REVIEW

**Comment by MarleenGilsing** [comment]
I redid level 2:
I seperated the new commands into a seperate tabs each.

I editted some adventure, so they only practise the new commands/concepts first. And I've rearranged them.

I added a second rock paper scissors adventure, for after they've learned the ask command.

I changed the introduction text to the what's next text from level 1. This gives a nice view of why we learn what we learn in level 2 and gives the student a sense of purpose (hopefully).



This is quite a lot of work, but I do think it improves Hedy's workflow and usability for teaching.  @Felienne I'd like you to test it before I take on other levels. No rush, I have other things on my to do list too.

**Comment by MarleenGilsing** [comment]
Went on to level 6, that's enough for now. 
@Felienne maybe we can take a look at it together next time we have a chance to meet up. I would like your thoughts on some things, but it's easier to do in a meeting than via github ;)

**Comment by Felienne** [comment]
> @Felienne maybe we can take a look at it together next time we have a chance to meet up. I would like your thoughts on some things, but it's easier to do in a meeting than via github ;)

Let me know if you

**Comment by MarleenGilsing** [comment]
I have split the keywords into adventures for all the levels now. The higher levels (as always) still need some more love. But that is an issue for another time. For now all levels have seperate keyword adventures and all have an introduction adventure that tells them why this level is useful (previously the what's next adventure).

**Comment by MarleenGilsing** [comment]
@Felienne All the levels are done now. The tests are failing because I used the whats next code in the intro. This means that the level 2 intro contains level 1 code and so on. I think we discussed that you could approve the 'wrong level' codes in the introductions, or would you rather have me change them?

**Comment by Felienne** [comment]
> @Felienne All the levels are done now. The tests are failing because I used the whats next code in the intro. This means that the level 2 intro contains level 1 code and so on. I think we discussed that you could approve the 'wrong level' codes in the introductions, or would you rather have me change them?

I will change the tests to update this so they don't keep failing!

**Comment by Felienne** [comment]
Ow and could you maybe write a little text about this change in Discord in #announcements? So teachers know and so Sabina can put this in the news letter

**Comment by MarleenGilsing** [comment]
> Ow and could you maybe write a little text about this change in Discord in #announcements? So teachers know and so Sabina can put this in the news letter

Will do! 

And now that I'm working on the slides I noticed that I hadn;t made a great start code for every new adventure. So I am changing them now in the same branch. I hope that doesn't cause any problems

**Pull request merged**
