### PR TITLE
📜 Adds workbooks in en and nl

### PR DESCRIPTION
**Pull request by MarleenGilsing**
Adds workbooks to pages

**How to test**

Follow these steps to verify this PR works as intended:

* Go to http://127.0.0.1:8080/for-teachers/workbooks/1 and witness the nice worksheets!!

image

### CODE REVIEW

**Comment by Felienne** [comment]
Setting this to draft, since I have to still add the translation defaults to weblate!

**Comment by Felienne** [comment]
Hi @boryanagoncharenko!

I added one key to show what I mean, if you understand how to finish this, please do (if not, I will do it maybe today or otherwise next week)

**Comment by boryanagoncharenko** [comment]
> Hi @boryanagoncharenko!
> 
> I added one key to show what I mean, if you understand how to finish this, please do (if not, I will do it maybe today or otherwise next week)

I added the strings for translation and fixed some content issues which caused a validation failure. Please check my translation of the question titles and descriptions.

I thought the only thing left for this PR is the Weblate work but it seems that the workbooks are not functional yet, is this correct? I am not sure I can take over the whole task because I lack the details, but if there is more work that you can delegate to me, just let me know.

**Comment by Felienne** [comment]
> > Hi @boryanagoncharenko!
> > I added one key to show what I mean, if you understand how to finish this, please do (if not, I will do it maybe today or otherwise next week)
> 
> I added the strings for translation and fixed some content issues which caused a validation failure. Please check my translation of the question titles and descriptions.
> 
> I thought the only thing left for this PR is the Weblate work but it seems that the workbooks are not functional yet, is this correct? I am not sure I can take over the whole task because I lack the details, but if there is more work that you can delegate to me, just let me know.

Hi @boryanagoncharenko!

Thanks for fixing the keys! The workbooks should be operational, via this link: http://127.0.0.1:8080/for-teachers/workbooks/1

Does that work for you?

If so, you can make the needed Weblate changes and approve!

**Review by boryanagoncharenko — APPROVED** [review]
LGTM! Just 2 things to note:
- There are some UI improvements that we can do for the workbooks, e.g. the radio buttons for correct/incorrect are not aligned etc. I will create a separate issue to iterate on the UI.
- For the English translation of the workbooks, I am certain we cannot use `codes`. The word (software) code is uncountable and should always appear in a singular form. If used as a countable noun, the word means non-software code e.g. crack the code, a strict code of conduct. I changed all instances of 'codes' to either 'programs' or just 'code'. Jesus and I recently corrected this in multiple other places. If you do not agree with this change, please let us know so that we stop correcting it.

**Pull request merged**
