### PR TITLE
[UI] Improves create multiple accounts UI

### LINKED ISSUE #3774: [UI] Improve account creation page
There are a few things we can do to make account creation easier, if we think of the perspective of a teacher that is adding ca. 30 accounts.

1. Add more than 1 (5? 10?) rows if we press +, now I have to push it 25 times. Or maybe make the default 20?

2. Make Generate Passwords a toggle and if turned on, remove the Password column altogether

3. Can we make a button for `Append classname` and/or `Append this string` to make it easier to generate unique names?

4. Ow and can we disable autocomplete by password tools:

image

I now have to manually empty 28x2 fields 😭

### PR DESCRIPTION
**Pull request by TiBiBa**
**Description**
In this PR we improve the UI of the multiple accounts creation page. The following changes are made:
- When pressing `+` 5 rows are added instead of one
- The `generate passwords` button is replace by a toggle
- When passwords are generated the input field is greyed out and disabled
- Add a button to prefix all usernames with the class name

**Fixes**
This PR fixes #3774.

**How to test**
Make sure you are a teacher and have class. Verify the new functionalities by adding students by creating new accounts.

### CODE REVIEW

**Review by Felienne — CHANGES_REQUESTED** [review]
Love it, the passwords in view is so much better!!

One little thing (apart from the conflicts LOL) Can we make it postfix instead of prefix?

I think henkie_klas1 is more clear for kids, and also in the interest of the teacher glancing over a class list, if they all start with klas1 it is hard to see who is who.

**Comment by TiBiBa** [comment]
> Love it, the passwords in view is so much better!!
> 
> One little thing (apart from the conflicts LOL) Can we make it postfix instead of prefix?
> 
> I think henkie_klas1 is more clear for kids, and also in the interest of the teacher glancing over a class list, if they all start with klas1 it is hard to see who is who.

Will do! And also fix the conflicts in one go.

**Comment by TiBiBa** [comment]
Should all be fixed!

**Review by Felienne — APPROVED** [review]

**Comment by TiBiBa** [comment]
Should all be fixed and ready for merge!

**Pull request merged**
