### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/Tutorials](https://hosted.weblate.org/projects/hedy/tutorials/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

* [Hedy/slides](https://hosted.weblate.org/projects/hedy/slides/)

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Parsons](https://hosted.weblate.org/projects/hedy/parsons/)

* [Hedy/Cheatsheets](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @boryanagoncharenko!

I thought this might be failing because the grammars were not up to date (I ran: https://github.com/hedyorg/hedy/blob/main/content/yaml_to_lark_utils.py) but there still seem to be an issue in a Russian program that I do not understand. 

Let me know if I need to dive in further or that you know how to deal with this?

**Comment by Felienne** [comment]
> The automatic script made changes
> 
> ## content/adventures/es.yaml
> There was a problem in a level 2 snippet, at adventures.turtle.levels.2.example_code_2:
> 
> Caution
> 
> We detected that `girar` is not usable with `ángulo`. Can you try changing `ángulo` to a number or input from `ask`? at line [5]
> 
> Translation source
> 
> ```
> {print} Dibujando figuras
> ángulo {is} 90
> {turn} angle
> {forward} 25
> {turn} ángulo  <---- ERROR HERE
> {forward} 25
> {turn} ángulo 
> {forward} 25
> ```
> 
> Translated version
> 
> ```
> imprimir Dibujando figuras
> ángulo es 90
> girar angle
> adelante 25
> girar ángulo  <---- ERROR HERE
> adelante 25
> girar ángulo 
> adelante 25
> ```
> 
> This snippet has been reverted to English.

This by the way is a very interesting error, because I think the problem is in line 2 (angle is not defined) and not in line 4! (but that is not the problem of the PR)

**Comment by boryanagoncharenko** [comment]
> Hi @boryanagoncharenko!
> 
> I thought this might be failing because the grammars were not up to date (I ran: https://github.com/hedyorg/hedy/blob/main/content/yaml_to_lark_utils.py) but there still seem to be an issue in a Russian program that I do not understand.
> 
> Let me know if I need to dive in further or that you know how to deal with this?

This PR changes the keyword for `ask` and the old version of this keyword is used in a public program. I "fixed" the error by manually correcting the file with the extracted public programs: #5810 

The new translation is better but it will brake all existing programs. It would be nice to support the old and the new keyword, so that old programs do not brake but we currently do not have that mechanism. On the other hand, the users will get a very nice message saying 'old version' is not a keyword, please use 'new version'. So maybe it is not that bad.

**Comment by Felienne** [comment]
> > Hi @boryanagoncharenko!
> > I thought this might be failing because the grammars were not up to date (I ran: https://github.com/hedyorg/hedy/blob/main/content/yaml_to_lark_utils.py) but there still seem to be an issue in a Russian program that I do not understand.
> > Let me know if I need to dive in further or that you know how to deal with this?
> 
> This PR changes the keyword for `ask` and the old version of this keyword is used in a public program. I "fixed" the error by manually correcting the file with the extracted public programs: #5810
> 
> The new translation is better but it will brake all existing programs. It would be nice to support the old and the new keyword, so that old programs do not brake but we currently do not have that mechanism. On the other hand, the users will get a very nice message saying 'old version' is not a keyword, please use 'new version'. So maybe it is not that bad.

We support different options for keywords, so in principe it should be doable, but maybe this is fine also in this case?

(also, I guess this can be closed now that #5810 is merged?)

**Pull request closed without merging**
