### PR TITLE
[UI] allow adventures to be added to multiple levels

### PR DESCRIPTION
**Pull request by hasan-sh**
**Idea**
In this PR, I'm converting how adventures relate to levels. Currently, an adventure can be added to one level only. The goal is to allow using adventures in different  levels. 

Fixes https://github.com/hedyorg/hedy/issues/3573

**Questions and Concerns:** 

- What happens if an adventure contains code that's not allowed (or is used differently) in different levels? 
  - Perhaps we could allow adding to levels that have the same restrictions?
  - Or just inform the teachers of this limitation. 

**How to test?**
- npm install
- add adventure to levels in the `customize-adventure` view

### CODE REVIEW

**Comment by hasan-sh** [comment]
Please don't mind the amount of commits! Most of which were a part of testing cypress, so see files changed for review!

**Comment by Felienne** [comment]
Hi @hasan-sh!

What is the status of this? I am trying to clean up the open PRs a bit.

**Comment by hasan-sh** [comment]
> Hi @hasan-sh!
> 
> What is the status of this? I am trying to clean up the open PRs a bit.

It's ready for review!

**Review by Felienne — APPROVED** [review]
Works great @hasan-sh!!

**Pull request merged**
