### PR TITLE
[BUG] Pygame features not working

### LINKED ISSUE #4035: [BUG] pygame features not working in Windows!
I can't believe I am only now seeing this but.... Pygame features don't seem to work in Windows (cc @ToniSkulj)

image

I will remove them from the adventures for now, and I guess that also takes presedence of fixing (it at all possible) over 4028.

### PR DESCRIPTION
**Pull request by ToniSkulj**
Fixes #4035

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @ToniSkulj!

Thanks for fixing, but this now reverts the cleanups in #4014, which does made the code a bit more readable. Is there a way to fix this bugs while keeping some of the files seperately?

**Comment by ToniSkulj** [comment]
> Hi @ToniSkulj!
> 
> Thanks for fixing, but this now reverts the cleanups in #4014, which does made the code a bit more readable. Is there a way to fix this bugs while keeping some of the files seperately?

No problem! I'm not 100% sure, I'm looking into it right now.

**Comment by ToniSkulj** [comment]
> Hi @ToniSkulj!
> 
> Thanks for fixing, but this now reverts the cleanups in #4014, which does made the code a bit more readable. Is there a way to fix this bugs while keeping some of the files seperately?



> Hi @ToniSkulj!
> 
> Thanks for fixing, but this now reverts the cleanups in #4014, which does made the code a bit more readable. Is there a way to fix this bugs while keeping some of the files seperately?

Found a way: [Fix issues with pygame prefix](https://github.com/hedyorg/hedy/pull/4037/commits/c42ebe92cea44e16c45e602c169ae37e8008c7e0)!

**Comment by ToniSkulj** [comment]
Changed the PR to https://github.com/hedyorg/hedy/pull/4039, closing this one. Something went wrong with the Cypress tests after merging main and I have no idea why 😅.

**Pull request closed without merging**
