### PR TITLE
[LANGUAGE] Add keyword translations in Telugu

### PR DESCRIPTION
**Pull request by sarangia-dev**
**Description**
Adds yaml file which translates the keywords from English to Telugu (en to te). Also, generated the highlighting syntax file and the associated lark file.

**Fixes _issue or discussion number_**
No related issue

**How to test**
- Running the website and clicking Telugu, typing keywords in the Hedy terminal and seeing if the keywords are highlighted. (Work in progress as of now, not working 100%)
- Using the existing translation  unit tests

### CODE REVIEW

**Review by TiBiBa — CHANGES_REQUESTED** [review]
Thanks for your contribution and the PR! I'm not sure why the folder static/fontawesome/css has changed. Could you reverse that change? Than I can take a look at your code changes.

**Comment by sarangia-dev** [comment]
> 

yep, not sure why that changed! will revert that

**Comment by Felienne** [comment]
Also, the highlighting and lark files do not have to be added, these will all be generated automatically

**Comment by Felienne** [comment]
Maybe it would be best to create a fresh PR with just [te.yaml](https://github.com/hedyorg/hedy/pull/3855/files#diff-c601375568208e4570447879bd330dc2b55ccbf0a3f56f6d51c7cee1765a0db5)? All the rest is not needed (including a manual test, because tests will be generated automatically)

**Comment by TiBiBa** [comment]
Fixed this in #3867.

**Pull request closed without merging**
