### PR TITLE
[LANGUAGE] added not in command for list

### PR DESCRIPTION
**Pull request by agusikhin**
**Description**

Adds "not in" functionality to level 5 and beyond for English. 

**Fixes _issue or discussion number_**

https://github.com/hedyorg/hedy/issues/3550

**How to test**

New tests are added in level 5

### CODE REVIEW

**Comment by agusikhin** [comment]
"not in" works, but the highlighting part is still in progress

**Comment by Felienne** [comment]
Thanks @agusikhi for your first Hedy contribution! It is too late in the evening now in CET so I will look at this later this week.

**Comment by Felienne** [comment]
Hi @agusikhin!

There seems to be an issue in the PR, not all tests pass.

Can you look into this and do you understand what is up? Of not please reach out on Discord so we can help out

**Comment by maryannho123** [comment]
Hi! We added 'not in' command to all the languages in English and it fixed the bug. It now passes all the unit test cases. Would it be helpful for us to translate the 'not in' commands via google translate or leave it for somebody else?

**Comment by maryannho123** [comment]
Hi! We added 'not in' command to all the languages in English and it fixed the bug. It now passes all the unit test cases. Would it be helpful for us to translate the 'not in' commands via google translate or leave it for somebody else?

**Comment by Felienne** [comment]
> Hi! We added 'not in' command to all the languages in English and it fixed the bug. It now passes all the unit test cases. Would it be helpful for us to translate the 'not in' commands via google translate or leave it for somebody else?

Great, I will try to have a look later today!

It is fine to leave it untranslated in other languages, translators can pick it up via Weblate lateron (and kids will then see it in English for now)

**Comment by Felienne** [comment]
Hi @agusikhi

I have tested the feature but it does not work yet, see:

image

image

Code (to copy paste):
```
item is ask 'What would you like to buy?'
stock is 'bread', 'milk', 'eggs'
if item not in stock
print 'Sorry, we do not sell that'
```

The PR also has no tests, which makes testing harder. Can you add a few tests in the levels that the new language feature should work in? You can look in tests/test_level/* what the tests look like, for example:

```
    def test_if_equality_unquoted_rhs_with_space_and_trailing_space_linebreak_print(self):
        code = textwrap.dedent("""\
        naam is James
        if naam is trailing space
        print 'shaken'""")

        expected = textwrap.dedent("""\
        naam = 'James'
        if naam == 'trailing space':
          print(f'shaken')""")

        self.multi_level_tester(code=code, expected=expected, max_level=7)
```

So the tests should have Hedy code in `code` and Python code in `expected` and match. This way we can see what you expect the Hedy code to produce.

**Comment by Felienne** [comment]
> Hi @Felienne ! I was actually going to open another issue related to this. We noticed that both the "in" and "not in" commands sometimes do not allow indexing to the last element. Basically if I have a list containing [1, 2, 3] they will work for 1 and 2 but not 3. I'm assuming this may be due to the list implementation? I can look into it more. 

Ah that might be a bug. Feel free to open an issue (also if you plan solving it yourself, just so we don't forget)

> We will add some additional tests shortly.

Perfect!

> Also, on my end, when working with the in and not in commands with strings, I have to put them in single quotes as the input such as 'eggs.' Is that correct or might this be an additional issue?

You mean in the UI, like this:

image

That is not what we would want, the kid would enter just `bread`.

**Comment by Felienne** [comment]
Hi @agusikhi I have marked this as draft until we have added the tests (so we keep an eye on what is still needed)

**Comment by agusikhin** [comment]
Hi @Felienne ! We added a couple of test cases for level 5. During our testing, we narrowed down the bug that was causing problems: https://github.com/hedyorg/hedy/issues/3789

Otherwise, "not in" should work normally. Thank you!

**Review by Felienne — APPROVED** [review]
Well done!! It all seems to work!!

(And we will look into https://github.com/hedyorg/hedy/issues/3789)

**Pull request merged**
