### PR TITLE
[TESTING, CYPRESS] 3808 testing fixing import errors in front end tests

### LINKED ISSUE #3808: [TESTING] Fixing import errors in front-end tests
This issue will include correcting the mistakes in importing navigation functions, more specificly GoToRegisterTeacher and goToRegister. We will remove unused functions.

### PR DESCRIPTION
**Pull request by CasProgram**
[TESTING, CYPRESS]

**Description**
As requested in Discord, I have adjusted the incorrect function imports in the front-end tests. Moreover, I have renamed file- and folder names according to the coding agreements.

**Fixes _issue or discussion number_**
Fixes #3808 

All tests should still work as before!

### CODE REVIEW

**Comment by martinj2001** [comment]
Looks good to me!

**Review by Felienne — CHANGES_REQUESTED** [review]
Thanks for the updates!

Not due to this PR, but due to #3782 (which changed the layout a bit) some teacher tests now fail:

image


Can you update these?

**Comment by Felienne** [comment]
Failing tests:

image

and 

image

**Comment by TiBiBa** [comment]
Fixed the `for-teachers` page issue, I think this PR is good to go!

**Comment by Felienne** [comment]
Yes, all tests now pass, but it is a bit of a hassle (f.e. I need to delete all classes of teacher1 or the tests will fail)

**Review by Felienne — APPROVED** [review]

**Pull request merged**
