### PR TITLE
[LANGUAGE] Allows guillemets for quoting

### LINKED ISSUE #3885: [LANGUAGE idea] Support «» for quoting
**Language idea incl level**
This now fails in level 5:

```
если a это нажмите
    печатать «Вы нажали А!»
иначе
    печатать «Вы нажали другую клавишу!»
```

But why should it? `«»` is an internationally used symbol for quoting (in French and Russian) and it would not be hard to allow it!

### PR DESCRIPTION
**Pull request by Felienne**
Fixes #3885

### CODE REVIEW

**Comment by antoineveldhoven** [comment]
lgtm!

I've added some tests and highlighting as well; https://github.com/antoineveldhoven/hedy/tree/guillemets

**Comment by Felienne** [comment]
> lgtm!
> 
> I've added some tests and highlighting as well; https://github.com/antoineveldhoven/hedy/tree/guillemets

Ah great, thanks! Can you push them onto this branch (we often add to each other's PRs in this repo, you should have the rights to do so)

**Comment by antoineveldhoven** [comment]
> > lgtm!
> > I've added some tests and highlighting as well; https://github.com/antoineveldhoven/hedy/tree/guillemets
> 
> Ah great, thanks! Can you push them onto this branch (we often add to each other's PRs in this repo, you should have the rights to do so)

I get a 403 when pushing to this branch...
```
Pushing to https://github.com/hedyorg/hedy
remote: Permission to hedyorg/hedy.git denied to antoineveldhoven.
fatal: unable to access 'https://github.com/hedyorg/hedy/': The requested URL returned error: 403
```

**Review by antoineveldhoven — APPROVED** [review]
LGTM

**Pull request merged**
