### PR TITLE
[CHORE] Unwrap Babel translations files

### PR DESCRIPTION
**Pull request by jpelay**
**Description**

A while ago we opened #4501 to add an add-on to Weblate so it wouldn't wrap files, we also changed the documentation to specify a `--no-wrap` option when extracting the labels. However, we are still running into problems where it seems like the files are actually wrapped. 

Looking into the git blame for the files, it seems like some lines haven't been changed in months, so maybe we actually need to change them manually by unwrapping all of them, and then send them to Weblate and see what happens?

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @jpelay!

I am looking into the addons in Weblate, and it seems we only have no-wrapping for yamls!

image

As far as I can see, there is no addon for po files outputting?

**Comment by Mark-Giesen** [comment]
@Felienne, you're looking at Adventures, which is a YAML component. Text is the PO component and this one does have a PO add-on set to no-wrapping. I'm not sure if unwrapping is triggered and if so when. We could try changing anything in a file and see if the complete file is unwrapped. If not, we could change all wrapped files by deleting one /n and see if Weblate does the rest.

image

**Comment by Felienne** [comment]
> @Felienne, you're looking at Adventures, which is a YAML component. Text is the PO component and this one does have a PO add-on set to no-wrapping. I'm not sure if unwrapping is triggered and if so when. We could try changing anything in a file and see if the complete file is unwrapped. If not, we could change all wrapped files by deleting one /n and see if Weblate does the rest.
> 
> image

Ah thanks @Mark-Giesen!! So it is really weird that the lines are now not wrapped in main.

Could it be that pre-commit does that? I am not sure whether that only works on py files?

**Comment by Mark-Giesen** [comment]
The PO add-on is set to no-wrapping, but I seem to remember I set it to "wrap on new-lines". This is the --no-wrap behaviour. Maybe someone changed it, or I remember incorrectly.

**Comment by Felienne** [comment]
> > Ah thanks @Mark-Giesen!! So it is really weird that the lines are now not wrapped in main.
> 
> They ARE wrapped, as I understand @jpelay. Lines that are old (not changed recently) are still wrapped. I assume these were wrapped in the passed and will only be unwrapped on a change.

Ah yeah sorry I meant weird that they are *wrapped*. So probably this PR will fix the issues (but we might want to wait until @Annelein's change is merged?)

**Comment by jpelay** [comment]
> Hi @jpelay!
> 
> I have merged all weblate PR's so we can do this again now (assuming you did it with a script and not manually haha)

Done!

**Review by Felienne — APPROVED** [review]
Hail mary that this will work and not break things 🤞!

**Pull request merged**
