### PR TITLE
[FIX] fix flaky cypress tests

### LINKED ISSUE #4455: [BUG] Flaky Cypress Tests
**Describe the bug**
In [this job ](https://github.com/hedyorg/hedy/actions/runs/6076542251/job/16484723178?pr=4435)there were 2 failing Cypress unrelated to what's being done in that PR. When I rerun the tests again on GH and local they worked again, so I'm making this issue as a note to self to investigate this.

The two failing tests are the following:
[BUG] Flaky Cypress Tests
 
```
1 failing

  1) Is able to download login credentials
       "before each" hook for "Passes":
     CypressError: Timed out retrying after 4000ms: `cy.type()` failed because this element is not visible:

`<strong id="username" class="inline-block w-1/2 px-2">teacher1</strong>`

This element `<strong#username.inline-block.w-1/2.px-2>` is not visible because its parent `<div#profile-change-body.profile-section-body>` has CSS property: `display: none`

 Running:  for-teacher_page/class_page/logs_page/search_button.cy.js                     (82 of 84)


  Is able to press the search button
    1) Passes
Cannot find coverage file /home/runner/work/hedy/hedy/tests/.nyc_output/out.json
Skipping coverage report


  0 passing (10s)
  1 failing

  1) Is able to press the search button
       Passes:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.view_class`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/for-teacher_page/class_page/logs_page/search_button.cy.js:10:7)


```

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

### PR DESCRIPTION
**Pull request by jtwaleson**
**Description**

When looking at the errors at https://github.com/hedyorg/hedy/actions/runs/6392606011/job/17350202761?pr=4581 I noticed that going to the logged in page sometimes redirects to the profile page, meaning the session is already logged in.

Cypress should run with test isolation but I'm not 100% sure how it's configured. The simplest thing I can think of is to clear the cookies + session + localstorage whenever we call login. That way we are sure that we have a fresh session.

I built a mini-test locally that tries to login 100x, which failed every time at some point. With this change it succeeds.

This fixes #4455 .

**How to test**

- Very difficult as it is flaky, but if you like you can wrap the login action locally 100x and seeing it fail consistently, and succeeding after this change.

**Checklist**

- [x] Contains one of the PR categories in the name
- [x] Describes changes in the format above
- [x] Links to an existing issue or discussion
- [x] Has a "How to test" section

### CODE REVIEW

**Review by Felienne — APPROVED** [review]
Let's see if this helps! Thanks for the detailed work!

**Comment by jpelay** [comment]
> Let's see if this helps! Thanks for the detailed work!

Nooo I was just going to make a comment hahaha :sweat_smile:

**Comment by jpelay** [comment]
Hi, Jouke!

I tried this in a CodeSpace and it didn't work for me, Cypress returned this error:

image


This was how I edited the login function:

```
export function login(username, password) {
    for (let i = 0; i < 100; i++) {
        cy.clearCookies();
        cy.clearAllLocalStorage()
        cy.clearAllSessionStorage();
        goToLogin();
        cy.get('#username').type(username);
        cy.get('#password').type(password);
        cy.get('#login_button').click();
        cy.wait(500);
    }
}
```

I'm i testing it right? Or I'm I doing something incorrectly?

**Comment by jtwaleson** [comment]
@jpelay I placed the loop in a separate test that called the loginForTeacher function and then logout. I didn’t see the error then. When I have some time and am back at my computer I’ll check out your case, thanks for verifying!

In any case the (hopeful) fix does not hurt, worst case it doesn’t fix the flakyness.

**Comment by jpelay** [comment]
> @jpelay I placed the loop in a separate test that called the loginForTeacher function and then logout. I didn’t see the error then. When I have some time and am back at my computer I’ll check out your case, thanks for verifying!
> 
> In any case the (hopeful) fix does not hurt, worst case it doesn’t fix the flakyness.

Yes you're right! Let's hope that this indeed fixes the error :D

**Pull request merged**
