### PR TITLE
Fixed the variable Prix in FR quiz question

### PR DESCRIPTION
**Pull request by Op1um3**
There is a variable name "prix" is the same for plural and singular in the French translation. The correction was the same as the original and we couldn't do the quiz question.

In this PR it is changed to "coût" which has a different plural like "price" in English. 

Also, in the same question there was a repeated price that is fixed.

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks for your first PR @Op1um3, and great catch (you can see we don't speak French!) I put a label first-timer here to welcome you and weblate-lock since this might conflict with Weblate. We will merge it when Weblate is stable!

**Comment by Felienne** [comment]
Thanks again, we are good to go now that Weblate is quiet. If you want to help out more, feel free to drop into our Discord (we have channels dedicated to translating too)

**Review by Felienne — APPROVED** [review]

**Comment by Op1um3** [comment]
I searched a little bit to find the discord and didn't find it is it possible for you to send me or where to look.
Thanks, I hope the merged work and I will do more translation!!!

**Comment by marcandre** [comment]
@Felienne Merci ♥️

@Op1um3 I believe this is the [discord.gg/FPUG4yyga2](https://t.co/C7pQJ5fQH2)

**Pull request merged**
