### PR TITLE
🧹 Refactor cypress tests (part 1)

### PR DESCRIPTION
**Pull request by Annelein**
Fixes the following tests for #4027 :

- [x] admin page
- [x] explore program page
- [x] feedback

### CODE REVIEW

**Comment by Annelein** [comment]
@jpelay is this what it should look like for example? Then I can start going through all tests and implement these changes!

**Comment by Annelein** [comment]
@jpelay @Felienne would it make sense to separate this issue into a few PR's? Otherwise it will be huge and then once in a while I can just change a few tests again.

**Comment by jpelay** [comment]
>@jpelay @Felienne would it make sense to separate this issue into a few PR's? Otherwise it will be huge and then once in a while I can just change a few tests again.

Sure!

**Comment by Annelein** [comment]
@jpelay then it's ready to be reviewed :)) Think it would be great if you could do it asap to avoid conflicts because it has changes in a lot of different places

**Review by Felienne — APPROVED** [review]
Looks great, thanks!!

**Pull request merged**
