### PR TITLE
🧪 Test for empty strings in English po file

### PR DESCRIPTION
**Pull request by Felienne**
Fixes the testing part of #5020

**How to test**
The tests should pass when the content has been fixed 

**Checklist**
Done? Check if you have it all in place using this list: (mark with x if done)

- [X] Contains one of the PR categories in the name
- [X] Describes changes in the format above
- [X] Links to an existing issue or discussion
- [X] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @hasan-sh!

Even with your new strings merged, there are still a few missing. I don't think this is a desired state, but maybe these strings are not used anymore? Potentially @jpelay or @Mark-Giesen can chip in? I do think we want this test to prevent issues in the future, but we need to make sure all strings are accounted for.

**Comment by hasan-sh** [comment]
> Hi @hasan-sh!
> 
> Even with your new strings merged, there are still a few missing. I don't think this is a desired state, but maybe these strings are not used anymore? Potentially @jpelay or @Mark-Giesen can chip in? I do think we want this test to prevent issues in the future, but we need to make sure all strings are accounted for.

Just added an extra check for the following case:

image

**Comment by hasan-sh** [comment]
Also i noticed an undesired behavior with pybabel update. In my other PR, after i extract the keys, some keys are removed from the `messages.pot` because they are unused. However, the update command still appends them to the end of each po file. See this  https://github.com/hedyorg/hedy/pull/5026/commits/7e358efff4732a502cf429ae32d912f0cc6b6950

**Comment by Felienne** [comment]
> Also i noticed an undesired behavior with pybabel update. In my other PR, after i extract the keys, some keys are removed from the `messages.pot` because they are unused. However, the update command still appends them to the end of each po file. See this [7e358ef](https://github.com/hedyorg/hedy/commit/7e358efff4732a502cf429ae32d912f0cc6b6950)

I am not sure this is undesired. The goal of this behaviour is that if we remove a string and later place it back (and that does happen), the translation is not lost. The string is commented out at the end of the file so it will not interfere with anything. 

Maybe this behaviour can be changed with a setting on Weblate but I think it is not too problematic. Is it causing you trouble?

**Comment by Felienne** [comment]
> > Hi @hasan-sh!
> > Even with your new strings merged, there are still a few missing. I don't think this is a desired state, but maybe these strings are not used anymore? Potentially @jpelay or @Mark-Giesen can chip in? I do think we want this test to prevent issues in the future, but we need to make sure all strings are accounted for.
> 
> Just added an extra check for the following case:
> 
> image

Thanks for the fix!! Happy you are cleaning up my half assed work 😅

**Comment by hasan-sh** [comment]
> Maybe this behaviour can be changed with a setting on Weblate but I think it is not too problematic. Is it causing you trouble?

No, it doesn't! Now i understand and it makes sense indeed, thanks for explaining.

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
