### PR TITLE
[FIX] Added brackets around keywords in adventures in de

### LINKED ISSUE #3537: [CONTENT] Use {} everywhere around keywords
As pointed out in #3514 some languages do not yet use {} around keywords for legacy reasons:

https://github.com/hedyorg/hedy/blob/1dfa0d9e11dee5646fb79c7d7960ad27be504ca9/content/adventures/de.yaml#L1402

Would be great if someone could fix that with a bit of prepping (here or in Weblate, both is fine by me!)

### PR DESCRIPTION
**Pull request by ana3999**
issue #3537

**Description**

Added brackets to the keywords.

**Addresses #3537 for German**

**How to test**

Users can check that they can now see that the keywords that are surrounded by brackets are now translated into the appropriate language. 

**Checklist**
Done? Check if you have it all in place using this list:*
  
- [X] Contains one of the PR categories in the name
- [X] Describes changes in the format above
- [X] Links to an existing issue or discussion 
- [X] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Felienne** [comment]
HI @ana3999 Sadly this now has conflicts, can you take a look at these? Don't worry about making mistakes, the tests will catch these.

**Review by Felienne — CHANGES_REQUESTED** [review]
Can you fix the conflicts? And ideally also make the fixes for other languages. 

Thanks!!

**Comment by ana3999** [comment]
Hi Felienne!

Sorry about the merge conflicts! Yes, I can try fixing those tonight, and
will continue to make fixes for other languages.

Thanks,
Ana

**Comment by Felienne** [comment]
There seems to be a small typo in de.yaml:

**Comment by Felienne** [comment]
Hi @ana3999!

I fixes a few tiny mistakes, I think we are good to go now! Thanks, this is a good step towards #3537

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
Congrats on your first merged PR @ana3999!!

**Pull request merged**
