### PR TITLE
[UI]Change the name of "program_header" for profile page

### PR DESCRIPTION
**Pull request by YanRui-Lv**
**Description**
**Changes** "program_header" in html from "my programs" to "programs".

Fixes (https://github.com/hedyorg/hedy/issues/4377)

**How to test**:

- Go to http://127.0.0.1:8080/my-profile
- In public profile, selecte the box that makes profile visible,  and update public profile.
- Go to https://127.0.0.1:8080/user/{your user name}
- See that program_header saying "Programs" instead of "My programs".

**Checklist**

- [x] Contains one of the PR categories in the name
- [x] Describes changes in the format above
- [x] Links to an existing issue or discussion 
- [x] Has a "How to test" section

### CODE REVIEW

**Review by jpelay — CHANGES_REQUESTED** [review]
Hi! @YanRui-Lv Thank you so much for your first contribution to our project!

I like the effort you put here, however, this is not the solution we're looking for. This would cause a Weblate blockage, meaning that our translator wouldn't be able to work on Hedy.

The solution we were looking for was this:

https://github.com/hedyorg/hedy/blob/644318414d59866eaac6e691fd930fff11607af1/templates/public-page.html#L86C27-L86C41

Replace `{{_('program_header')}}` in that file for: `{{_('programs')`}}.

So, instead of all of this changes to the `messages.po` files, you'd just need to edit that single lline!

**Comment by YanRui-Lv** [comment]
Thank you for your advice!

**Comment by Felienne** [comment]
I have made the changes as suggested above

**Comment by Felienne** [comment]
Working as expected now:

image

**Review by Felienne — APPROVED** [review]

**Review by jpelay — APPROVED** [review]

**Pull request merged**
