### PR TITLE
[DOCS] Readme Update

### PR DESCRIPTION
**Pull request by AnderMendoza**
Hello, in this PR I am adding links to the existing issue templates in the project, to speed up the issue generation process for future contributors. Also add the logo and edit the content by removing all the html to keep only markdown code, also, add thanks to the contributors of this project in the final part.

Attached screenshot of the start:
image

Attached screenshot of the end:
image

### CODE REVIEW

**Review by TiBiBa — APPROVED** [review]
I love this improvement!

**Comment by AnderMendoza** [comment]
> I love this improvement!

Thanks, what would it take for the PR to be accepted?

**Comment by TiBiBa** [comment]
> > I love this improvement!
> 
> Thanks @TiBiBa , what would it take for the PR to be accepted?

It's already accepted! But I've been out of the running for a while as a Hedy contributor. So just to be sure, let's wait until @Felienne or @jpelay has had time to take a look as well before we merge this.

**Comment by yilmazdurmaz** [comment]
that combined image of contributors at the end, should you have it?

**Comment by Felienne** [comment]
> that combined image of contributors at the end, should you have it?

I like it! People spend a lot of time on Hedy!

**Comment by Felienne** [comment]
> > > I love this improvement!
> > 
> > 
> > Thanks @TiBiBa , what would it take for the PR to be accepted?
> 
> It's already accepted! But I've been out of the running for a while as a Hedy contributor. So just to be sure, let's wait until @Felienne or @jpelay has had time to take a look as well before we merge this.

Because you are a first time contributor, I need to manually run the tests, doing so now. If all tests pass (which I do expect!) it will be aut-merged.

**Pull request merged**
