### PR TITLE
[CONTENT] Fix typo in default adventure lvl 10

### LINKED ISSUE #4616: [CONTENT] Introduction: Level 11 has typo
**Describe the issue**
Level 11: Introduction
"You have reached level 10, you're doing great! "

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**Expected text**
You have reached level 11, you're doing great!

### PR DESCRIPTION
**Pull request by TiBiBa**
This PR addresses #4616 for English.

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks @TiBiBa! Did you we check if this string also occurs on other languages? Would be nice if we fix those too with a ctrl-f!

**Comment by TiBiBa** [comment]
> Thanks @TiBiBa! Did you we check if this string also occurs on other languages? Would be nice if we fix those too with a ctrl-f!

I did not check yet. Thought that Weblate would fix this and set other languages as "need an update". But indeed nicer to fix directly, will take a look tomorrow!

**Comment by Felienne** [comment]
> > Thanks @TiBiBa! Did you we check if this string also occurs on other languages? Would be nice if we fix those too with a ctrl-f!
> 
> I did not check yet. Thought that Weblate would fix this and set other languages as "need an update". But indeed nicer to fix directly, will take a look tomorrow!

Yes, Weblate will do that but if it is such a small fix, it is nice if we can do it in one go. But it looks like the string is only there in this form in En: 
image

So if Weblate is merged, this can go in!

**Comment by yilmazdurmaz** [comment]
> But it looks like the string is only there in this form in En
You can have search on Weblate itself and it will show a list for all languages as the main language has it.

I have checked this string on Weblate. Only 7 languages that are most active have this number: English, Spanish, French, Turkish, Swedish, Korean, Catalan (Dutch translation just welcomes and does not use the number, a different approach).

You can simply edit the numbers in these language files here or I may correct them again on Weblate. Doing this on Weblate won't require any lock.

Also, all other languages still have the very old unchanged strings about "for" topic, at least two different versions. I haven't checked yet but it is possible these old strings were shifted to the next "for" tab. So, a check on the string of the "for" tab of level 11 would benefit from already-made old translations some languages have.

I can make both the corrections and the check/copy on Weblate. I am not multi-lingual (only qualified on English and Turkish), but understand base language structures. I use Weblate's string history, keywords, and some translator extensions to see if a translation makes sense. Just let me know if you want such work.

**Comment by Felienne** [comment]
> > But it looks like the string is only there in this form in En
> 
> You can have search on Weblate itself and it will show a list for all languages as the main language has it.
> 
> I have checked this string on Weblate. Only 7 languages that are most active have this number: English, Spanish, French, Turkish, Swedish, Korean, Catalan (Dutch translation just welcomes and does not use the number, a different approach).
> 
> You can simply edit the numbers in these language files here or I may correct them again on Weblate. Doing this on Weblate won't require any lock.
> 
> Also, all other languages still have the very old unchanged strings about "for" topic, at least two different versions. I haven't checked yet but it is possible these old strings were shifted to the next "for" tab. So, a check on the string of the "for" tab of level 11 would benefit from already-made old translations some languages have.
> 
> I can make both the corrections and the check/copy on Weblate. I am not multi-lingual (only qualified on English and Turkish), but understand base language structures. I use Weblate's string history, keywords, and some translator extensions to see if a translation makes sense. Just let me know if you want such work.

Yes, if you are willing to make the change in other languages, that would be very welcome!

**Comment by yilmazdurmaz** [comment]
@Felienne for me, working on Weblate became easier because of its own history and search mechanism.

you may approve and merge this PR, and then lock and sync Weblate. I will do the rest on Weblate. I will begin when I see these steps here and then on Weblate

Alternatively, I may also do this PR's change on source again on Weblate too. This will delay the use of the changed string (until you merge the next Weblate PR with my changes) but also remove the 4-steps you need (if lock&sync takes too long or complex). Just tell me so if this one suits you better.

**Comment by yilmazdurmaz** [comment]
> but also remove the 4-steps you need (if lock&sync takes too long or complex).

to clearify this, I meant it removes only the initial lock&sync steps. merging Weblate commits at the end would still need them.

**Comment by Felienne** [comment]
Fine if you fix it on Weblate! I assigned it to you so we don't forget, it would be great if you could ping on the Weblate PR with the issue number when it is ready.

**Review by Felienne — APPROVED** [review]

**Pull request merged**
