### PR TITLE
[CONTENT] Fixes minor mistakes in the level 9 English quiz and translates the Dutch quiz.

### LINKED ISSUE #3998: [CONTENT] Level 9 quiz translations
**Describe the issue**
The level 9 quiz is not yet properly translated to Dutch. The English version of the quiz also contains minor mistakes.

**Note:** I will fix this today.

### PR DESCRIPTION
**Pull request by sjensen19**
Fixes minor mistakes in the level 9 English quiz and translates the Dutch quiz.
**Description**
Fixes minor mistakes in the English quiz
Translates the level 9 english quiz to dutch

**Fixes #3998**

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

I have moved level 9 and translated Q1,2,3, and 5. Could you finish the translations (or maybe @sjensen19 wants to do it?)

I have skipped Q4 for now, I also find it very hard in English (`'I was looking for you!'` and `'Ill keep looking'` are very similar) and 2 and 4 are the same answer in the original En version) 

Can you improve that question too?

**Comment by sjensen19** [comment]
@Felienne I already started translating, but I am not done yet. Will finish this today or tomorrow!

**Comment by Felienne** [comment]
> 

Fantastic! In that case, @MarleenGilsing and me will stop pushing on this PR!

**Comment by Felienne** [comment]
Ah I forgot Q4 still needs fixing (I will pick it up)

**Review by Felienne — APPROVED** [review]

**Pull request merged**
