### PR TITLE
[UI] Creating Tags

### LINKED ISSUE #4603: [UI idea] Allow teachers to tag adventures
This is a large for our new team member @hasan-sh who will (among other things) work on content-management.

Text from our proposal:

_"To make content better searchable, two separate approaches are needed.
Firstly, we need to add meta data to content. For example, teachers might want to tag what age group content is designed for, what (natural) language it is written in, what learning outcomes it aims for and what general themes occur in it. We will engage the current community to determine what metadata tags are needed. For existing content this means examining it and tagging it manually, for new content it means that our upload system will have to support tags. "_

Some steps to take:
* Add a tag option to the adventure author page (https://hedy.org/for-teachers/customize-adventure/)
* Create a database tabel to hold tags
* Make sure tags can be translated, probably Spanish people will want to use Spanish tags. 
* Think of a good UI to communicate existing tags incl translations

### PR DESCRIPTION
**Pull request by hasan-sh**
Stap one of the  (content-management) improvement. 

Fixes #4603 
Depends-on [#4722](https://github.com/hedyorg/hedy/pull/4722)

**Features**
- teachers can tag adventures in the `customize-adventure` view
- tags are created once and never removed
- so, tags can be added to and removed from adventures only

### CODE REVIEW

**Comment by jpelay** [comment]
Hi, Hasan! Is this PR still in progress? If so, can you mark it as a Draft? That way is easier for me and Felienne to know which PRs to take a look first.

**Comment by Felienne** [comment]
Thanks @hasan-sh, I will try to take a look today!

**Comment by Felienne** [comment]
Tagging works great @hasan-sh! I have one question though, if a teacher adds a tag, should we search the existing tags and suggest these? Otherwise I worry a bit we will soon have "grade 7" and "7th grade" etc. So I would prefer the add box to also be a search box suggesting similar tags:

image

If you are planning to do this in a separate PR, that is also totally fine by me! Then let's merge this and open an issue for the search within the tagging (which is different from search adventures by tag)

**Comment by Felienne** [comment]
(also, note to self, we should not forget to add this table on test and prod!)

**Comment by hasan-sh** [comment]
> Tagging works great @hasan-sh! I have one question though, if a teacher adds a tag, should we search the existing tags and suggest these? Otherwise I worry a bit we will soon have "grade 7" and "7th grade" etc. So I would prefer the add box to also be a search box suggesting similar tags:
> 
> image
> If you are planning to do this in a separate PR, that is also totally fine by me! Then let's merge this and open an issue for the search within the tagging (which is different from search adventures by tag)

Yes we should and will do that. I remember we talked about it and agreed to make it a separate issue. I can work on it tomorrow.

**Comment by Felienne** [comment]
This should be good to go when I have merged Weblate!

**Review by Felienne — APPROVED** [review]

**Comment by Felienne** [comment]
Grrrrr that "depends-on" syntax of Mergify did not do the job :(

**Pull request merged**
