### PR TITLE
🧹 Refactor Pygame Code

### PR DESCRIPTION
**Pull request by ToniSkulj**
PR for removing the use of Pygame within Hedy.
We still want to keep the functionality of "if button pressed".

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @jpelay and @ToniSkulj!

I have updates all level tests, except for one that I did not know how to deal with (I commented that out in https://github.com/hedyorg/hedy/pull/5117/commits/0061806df62fa378fc10c7b86b416f6efb7920eb) 

I am not sure if more it needed at the moment, so I will leave this to you two for now!

**Comment by ToniSkulj** [comment]
Hi @Felienne!
Thank you for adding the tests! I fixed the level 8 test, all tests should be passing now.

The only case that remains is when the user uses elifs without an else. Currently, it does not do anything.
I will keep you updated when I find something to solve that.

**Comment by Felienne** [comment]
> Hi @Felienne! Thank you for adding the tests! I fixed the level 8 test, all tests should be passing now.
> 
> The only case that remains is when the user uses elifs without an else. Currently, it does not do anything. I will keep you updated when I find something to solve that.

Awesome, thanks so much for seeing this through! If you have an idea for the elif/else issue, do keep us posted. Otherwise we can always throw an exception and say: you can't use elif in pressed without else.

**Review by jpelay — APPROVED** [review]
This is such a great work!!! Thank you SO MUCH for this! This is a great PR and everything worked, but a couple of things that I fixed myself.

There's an issue still with the debugger, but there's an issue opened fort that already on #4765!

**Pull request merged**
