### PR TITLE
💻 create super teacher

### LINKED ISSUE #5371: 💻 Create superteacher account
Let's create a type of account called "superteacher" that can do things like:

* Approve teacher requests
* Delete adventures (#5369)
* Read feedback questions (introduced in #5215)
* Connect teachers that want support (introduced in #5212)

Scope of this would be:
* Create a new type in the database
* Create a way to turn teacher accounts into superteachers (invite code? approve by admin?)
* Make new pages to do the above tasks

### LINKED ISSUE #5422: admin can create superteachers (back/frontend)
- admin adds superteachers by username

### LINKED ISSUE #5443: creating super-teachers

### LINKED ISSUE #5451: Super teacher can delete adventures

### LINKED ISSUE #5474: Super teachers can connect teachers for support

### PR DESCRIPTION
**Pull request by hasan-sh**
Fixes #5443
Fixes #5422 
Fixes #5474
Fixes #5371
Fixes #5451 

**How to test?**
First you have to make your teacher account a super teacher. Do so by:
- logging in as an admin,
- go to users overview,
- then mark your account as super teacher.
> Test this works expectedly!

Then log in with your super teacher account, now you see `Super teacher` in the nav bar. With this you can:
- view feedback submitted by users,
   - if there's no feedback, create one so that you could see it.
   - you should see then all info related to it. 
   - you can also click on create issue, which takes opens a new tab with a github issue filled with the selected feedback information.
- view public adventures
   - and delete any adventure
- view support teacher page
   - connect one teacher to another  (this feature isn't significant for now)
   - what's important is to get a view of teachers who indicated they needed support
   - 

**DB changes**
- added a `is_super_teacher (0 or 1)` field to the user table.

### CODE REVIEW

**Comment by Annelein** [comment]
@hasan-sh I added that it also fixes #5451 right?

**Comment by hasan-sh** [comment]
> @hasan-sh I added that it also fixes #5451 right?

Yes indeed!

**Comment by jpelay** [comment]
Hi! In the PR description it says

> what's important is to get a view of teachers who indicated they needed support

But is there a way for a teacher to indicate if they need support? Everything else works, so I would just like to know this in order to approve the PR 😄

**Comment by Annelein** [comment]
There is! But @Felienne do we only want this option when creating an account?
Could it be that they don't know if they need help when signing up, but later on they figure they need help, there is no way to ask for it, right?

Screenshot 2024-06-05 at 10 26 00

**Comment by Felienne** [comment]
> There is! But @Felienne do we only want this option when creating an account? Could it be that they don't know if they need help when signing up, but later on they figure they need help, there is no way to ask for it, right?
> 
> Screenshot 2024-06-05 at 10 26 00

Not right now, but let's do that separately (and simple, f.e. with a link via email)

**Comment by Annelein** [comment]
Then it's ready @jpelay

**Comment by jpelay** [comment]
> There is! But @Felienne do we only want this option when creating an account? Could it be that they don't know if they need help when signing up, but later on they figure they need help, there is no way to ask for it, right?
> 
> Screenshot 2024-06-05 at 10 26 00

Thanks didn't notice it!

**Review by jpelay — APPROVED** [review]
Thanks!! Great work!

**Pull request merged**
