### PR TITLE
[FIX] Highlight unterminated quoted strings differently than correctly terminated quoted strings.

### LINKED ISSUE #3768: [HIGHLIGHTING] Do not highlight strings that do not end in a quote
From level 4 on, strings need to be enclosed in quotes, but the highlighter is not as strict:

image

I know that in most systems it is common practice to also highlight unclosed strings:

image

But I think in our case it would make sense to make `'Bonjour le monde` white and not purple in this code:

```
print 'Bonjour le monde
```

We could consider making the `'` purple? I think I need to see that in action to decide.

### PR DESCRIPTION
**Pull request by antoineveldhoven**
**Description**

- Remove styling for unterminated quoted strings in Level 4;
For educational purposes (the essence of Level 4) do not highlight incorrect termination of quotations.
- Mark unterminated quoted strings as invalid for Level 5 and above

**Fixes #3768**

**How to test**

***Level 4 and above***
- Go to http://localhost:8080/hedy/4#default
- Observe the 2nd example code
Scherm­afbeelding 2023-03-22 om 15 11 45

**Checklist**
Done? Check if you have it all in place using this list:*
  
- [x] Contains one of the PR categories in the name
- [x] Describes changes in the format above
- [x] Links to an existing issue or discussion 
- [x] Has a "How to test" section

### CODE REVIEW

**Comment by antoineveldhoven** [comment]
> Ow yes and the highlighting has tests that are now broken, do let us know if you need help to fix them!

First time commiter here :raising_hand_man: :man_facepalming:
Will have a (better) look at the tests and resubmit my PR.

**Comment by Felienne** [comment]
> > Ow yes and the highlighting has tests that are now broken, do let us know if you need help to fix them!
> 
> First time commiter here 🙋‍♂️ 🤦‍♂️ Will have a (better) look at the tests and resubmit my PR.

No problemo! That was actually why the tests did not run (first timers have to be manually approved). Do reach out if we can help!

**Comment by antoineveldhoven** [comment]
> > > Ow yes and the highlighting has tests that are now broken, do let us know if you need help to fix them!
> > 
> > 
> > First time commiter here 🙋‍♂️ 🤦‍♂️ Will have a (better) look at the tests and resubmit my PR.
> 
> No problemo! That was actually why the tests did not run (first timers have to be manually approved). Do reach out if we can help (here or in Discord)

Thnx for the review; I've updated this PR, can you have another look, assuming the tests run fine this time 😜

**Comment by Felienne** [comment]
> > > > Ow yes and the highlighting has tests that are now broken, do let us know if you need help to fix them!
> > > 
> > > 
> > > First time commiter here 🙋‍♂️ 🤦‍♂️ Will have a (better) look at the tests and resubmit my PR.
> > 
> > 
> > No problemo! That was actually why the tests did not run (first timers have to be manually approved). Do reach out if we can help (here or in Discord)
> 
> Thnx for the review; I've updated this PR, can you have another look, assuming the tests run fine this time 😜

Let's see ;) I will also send you an invite to the repo, that way your PRs will run the tests automatically!

**Review by Felienne — APPROVED** [review]
Thanks @antoineveldhoven, all good now! 

And congrats on getting your first PR approved!!! 🥳

**Comment by antoineveldhoven** [comment]
> Thanks @antoineveldhoven, all good now!
> 
> And congrats on getting your first PR approved!!! 🥳

thnx, also for the fix in the print test!

**Comment by Felienne** [comment]
I have also opened a Discussion for your other idea: #4169 Will ask a few teachers to chip in with their opinion!

**Pull request merged**
