### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Parsons](https://hosted.weblate.org/projects/hedy/parsons/)

* [Hedy/slides](https://hosted.weblate.org/projects/hedy/slides/)

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

* [Hedy/Cheatsheets](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

* [Hedy/Tutorials](https://hosted.weblate.org/projects/hedy/tutorials/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by yilmazdurmaz** [comment]
@Felienne I closed #3520 and #4616 as I finished editing on Weblate. we got the translation here in this commit.

the current build error for the moment is caused on the `turn` command for Serbin translations. I will make a separate issue about that because the code seems alright (not even translated)

**Comment by Felienne** [comment]
> @Felienne I closed #3520 and #4616 as I finished editing on Weblate. we got the translation here in this commit.
> 
> the current build error for the moment is caused on the `turn` command for Serbin translations. I will make a separate issue about that because the code seems alright (not even translated)

No need for an issue, I know the problem and I will fix it!

**Comment by Felienne** [comment]
> @Felienne I closed #3520 and #4616 as I finished editing on Weblate. we got the translation here in this commit.

Thanks but usually we close issues when the corresponding PR is merged, so it is better to mention the issues in the PR (for now we can leave this as is, this note if just for future reference).

**Review by Felienne — APPROVED** [review]

**Comment by yilmazdurmaz** [comment]
alright, new check: adding/changing keywords needs attention.

and, note taken: not closing issues before actual full merge ;)

**Comment by Felienne** [comment]
> alright, new check: adding/changing keywords needs attention.
> 
> and, note taken: not closing issues before actual full merge ;)

Yes specifically translating an else requires a change to the grammar (which I always take care of)

**Pull request merged**
