### PR TITLE
[CONTENT] Improves Parsons Puzzels and adds new ones

### PR DESCRIPTION
**Pull request by MarleenGilsing**
Improves Parsons Puzzels and adds new ones

### CODE REVIEW

**Comment by MarleenGilsing** [comment]
@Felienne Deze klopt nu :)

**Comment by MarleenGilsing** [comment]
Now it's correct in all languages.

**Comment by MarleenGilsing** [comment]
Yay! 🥳

**Comment by Felienne** [comment]
Goed werk! Ik ga weblate mergen en dan al jouw PRs erdoor!

**Review by Felienne — APPROVED** [review]
Nice improvements @MarleenGilsing! This might mess up the open weblate but I will look at it.

**Pull request merged**
