### PR TITLE
Show error locations inside the editor itself

### PR DESCRIPTION
**Pull request by bjorn3**
image

image

Keeping it as a draft until I have fixed the glitch on error hover and ~~added squiggly lines (if possible in ace)~~ (can't find how to do this).

### CODE REVIEW

**Comment by bjorn3** [comment]
> until I have fixed the glitch on error hover

I have now replaced it with a fixed message.

image

> I have not find squiggles either but you should be able to highlight with a color, see: https://stackoverflow.com/questions/16024721/how-can-i-highlight-multiple-lines-with-ace/16024998#16024998

I will try that.

**Comment by Felienne** [comment]
> > until I have fixed the glitch on error hover
> 
> I have now replaced it with a fixed message.
> 
> image
> 
Do we have to have a message there? This message I think might not add much versus no message at all? If possible could we get the contents of the error there without the position? So: "you typed a space but that is not allowed"?

**Comment by bjorn3** [comment]
It now looks like

image

**Comment by Felienne** [comment]
> I have changed it to an empty error box now.

Cool certainly an improvement over what we have! Will check the final version out later today.

**Pull request merged**
