### PR TITLE
🪲 Embedded editor broken due to missing adventure name

### PR DESCRIPTION
**Pull request by TiBiBa**
This MR fixes an issue with the embedded editor due to a non-existing adventure object. Adding this check should fix it.

### CODE REVIEW

**Comment by Felienne** [comment]
HI @TiBiBa! I guess this needs to be deployed quickly? 😬 If @jpelay approves I will deploy!

**Comment by TiBiBa** [comment]
> HI @TiBiBa! I guess this needs to be deployed quickly? 😬 If @jpelay approves I will deploy!

Yes, if we could deploy this today that would awesome! Thanks for the quick response, I just tested the fix and it seems to solve the issue. Will prioritize the embedded view testing to prevent this from happening again in the future.

**Comment by Felienne** [comment]
Deploying now! And yes adding tests will make your own future life less stressful :D

**Comment by TiBiBa** [comment]
> Deploying now! And yes adding tests will make your own future life less stressful :D

Unfortunately it is still not working, is there someway I can verify what code is running on production? The same error still seems to exist.

**Review by jpelay — APPROVED** [review]
Thanks for fixing it so quickly!

**Comment by jpelay** [comment]
@Felienne I think we need to redeploy? Now that this is merged to main

**Comment by TiBiBa** [comment]
> @Felienne I think we need to redeploy? Now that this is merged to main

Yes I think so too! @jpelay can you deploy or can only @Felienne do this?

**Comment by jpelay** [comment]
> Yes I think so too! @jpelay can you deploy or can only @Felienne do this?

No, she's the only one who can deploy.

**Comment by Felienne** [comment]
> > Deploying now! And yes adding tests will make your own future life less stressful :D
> 
> Unfortunately it is still not working, is there someway I can verify what code is running on production? The same error still seems to exist. **Edit:** The last commit is 1acc76. Should this be merged first or can you deploy this PR as well?

Sorry, my bad! Your merge just missed the deploy train because the tests were still running. Now it should be there, can you check again?

**Pull request merged**
