### PR TITLE
[FIX] order of slides' levels & pages for Turkish only

### PR DESCRIPTION
**Pull request by yilmazdurmaz**
**Description**

I manually reordered slide pages and levels for Turkish language. I first ordered page numbers in slides, then reordered levels. Also added a little touch to the last page of level 2. So from the file's perpective the things are alright.

Please check if editing the file this way is alright from the project's perspective and that of Weblate.

**Fixes** the ordering issue on https://github.com/hedyorg/hedy/issues/4480

- [x] Links to an existing issue or discussion

### CODE REVIEW

**Comment by Felienne** [comment]
Thanks a lot for this @yilmazdurmaz, but we are working on a more generic solution, sorting all languages so the problem does not occur in the future, and we hope to finish that soon (See #4557) So I am closing this one.

**Comment by yilmazdurmaz** [comment]
@Felienne Slides are one of the most important things for teachers before starting their classes and levels.

Since I translated everything except high level quizzes, I want to start sharing Hedy with Turkish people. Though translated, this page ordering problem prevents me from doing that. It is like a drop of poison onto a finely cooked meal.

Please assign a priority to re-ordering slide pages; unlike other yaml files, levels and pages are marked with numbers in slides.

Or let me reopen this PR.

**Comment by Felienne** [comment]
> Please assign a priority to re-ordering slide pages

Hi @yilmazdurmaz, we are currently working on a fix and we are really trying to get that out as soon as we can! You can follow the progress on https://github.com/hedyorg/hedy/pull/4557.

I could potentially merge this fix, but only if weblate is not active (otherwise everything will be in conflict). Should that happen, I promise I will do my best to merge this in between other PRs, but just know we are working on it. It should really be fixed within a few days.

**Comment by Felienne** [comment]
@yilmazdurmaz, I have closed Weblate, let's see if this does not cause conflicts!

**Review by Felienne — APPROVED** [review]

**Pull request merged**
