### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Parsons](https://hosted.weblate.org/projects/hedy/parsons/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/Commands](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/Tutorials](https://hosted.weblate.org/projects/hedy/tutorials/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by TiBiBa** [comment]
New GitHub actions flow for only testing the snippets when the author of the pr is 'weblate' seem to work. This PR seems to fail on some unrelated issues in the translations themselves.

**Comment by Felienne** [comment]
> New GitHub actions flow for only testing the snippets when the author of the pr is 'weblate' seem to work. This PR seems to fail on some unrelated issues in the translations themselves.

Yes those issues already existed before the PR!

**Comment by TiBiBa** [comment]
> > New GitHub actions flow for only testing the snippets when the author of the pr is 'weblate' seem to work. This PR seems to fail on some unrelated issues in the translations themselves.
> 
> Yes those issues already existed before the PR!

All right! What would be the best approach to fix this? First stop weblate? I committed a fix to this branch concerning the French failing tests but for some reason it is not found on this branch. Not sure what went wrong there...

**Comment by Felienne** [comment]
Yeah the force push removes yourself prior commits but you can repush them.
But it is ok to let me or Mark deal with Weblate for now! If you have a
reason it needs to be merged I can do so!

**Review by Felienne — APPROVED** [review]

**Pull request merged**
