### PR TITLE
🧹 Remove superflous code in generated pygame code frontend

### PR DESCRIPTION
**Pull request by mani1986**
Fixes (part of) 3966

**How to test**
Follow these steps to verify this PR works as intended:
* Run `if a is pressed print 'a' else print 'other'` in Level 5 / Introduction
* Press `a` on keyboard.

**Checklist**
Done? Check if you have it all in place using this list: (mark with x if done)

- [x] Contains one of the PR categories in the name
- [x] Describes changes in the format above
- [x] Links to an existing issue or discussion
- [x] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Felienne** [comment]
Hi @mani1986 and @ToniSkulj!

I have updated the tests for level 5 but in level 8 I think there might be other things still amiss with the PR? I get an error about an extra argument?

image

Let me know how to fix that and I can take care of the tests, no problem!

**Comment by Felienne** [comment]
Also, for reasons I don't really understand, this PR seems to have all commits from all other PRs too?

I have tried to cherry pick the changes in #5173 but I am not sure I did it correctly, so please fix that PR if it is the right way!

**Comment by Felienne** [comment]
> > Hi @mani1986 and @ToniSkulj!
> > I have updated the tests for level 5 but in level 8 I think there might be other things still amiss with the PR? I get an error about an extra argument?
> 
> Hi @Felienne! You are right. It seems that I had forgotten to push some commits the last time. I pushed them into #5117.

Thanks!! I am not entirely sure of the relationship between this PR and #5117, should one go in before the other?
> 
> > Also, for reasons I don't really understand, this PR seems to have all commits from all other PRs too?
> 
> Hmmm, not sure what happened here. Maybe we can merge your updates for the tests in level 5 into #5117? 

Done!

> EDIT: Maybe also the front-end changes made by @mani1986? I hope to have some more time this weekend to at least make it functional.

Thanks!!

**Comment by ToniSkulj** [comment]
Hi @mani1986! I cherry-picked your front-end commits into #5117. It seems that something weird happened with this PR,
all other PR commits seem to be merged as well.

Would you mind me if I close this PR? We can continue working on #5117.

**Pull request closed without merging**
