### PR TITLE
💻 Go to next student button on reviewing

### LINKED ISSUE #5772: 💻 "Add next student" in the teachers view of code submission
When I look at the students's submission, I now open them all one my one, but it would be amazing if the first row, this one:

image

Would also have an eye button, which would open all tried programs (the ones with an eye) and open them all in new tabs.

### PR DESCRIPTION
**Pull request by jpelay**
Adds two buttons, so we can decide which one to keep tomorrow in the meeting:

image

1. The "Go to next student" button, does what the original issue suggests, a button to review the next student that completed this adventure, i.e: iterating over columns.

2. The "Go next" button goes to the next adventure submitted by the student, i.e: iterating over rows.

I added both to see which one would you guys prefer.

Fixes #5772

**How to test**

*  Log in as teacher1 and go to the class.
* Click the eye icon in one of the programs.
* Check that when you click the Go next button you go to the next adventure
* Check that when you click go next student you go to the next student.

### CODE REVIEW

**Comment by jpelay** [comment]
@Felienne Do you want me to keep both buttons or do you want me to remove one of them?

**Comment by Felienne** [comment]
> @Felienne Do you want me to keep both buttons or do you want me to remove one of them?

Ah yeah, both are next! Shall we make the "go next" then say "Go to next student"? That is a nice complement over "Go to next adventure"

**Comment by jpelay** [comment]
> Ah yeah, both are next! Shall we make the "go next" then say "Go to next student"? That is a nice complement over "Go to next adventure"

Done!

**Review by Felienne — APPROVED** [review]
Thanks @jpelay!!!

**Pull request merged**
