### PR TITLE
[CLEANUP] Make Hedy PEP8 compliant

### PR DESCRIPTION
**Pull request by jpelay**
**Description**

Since #3410 we introduced a git pre-commit hook to lint modified code. However, much of the Hedy codebase is still not PEP8 compliant, in this PR we'll change that by applying autopep8 to the whole codebase with the following parameters:

```
autopep8 --in-place --max-line-length 120  -aaa --jobs 0 [files]
```
A few changes have been made to the pre-commit hook:
* The max line length now is 120
* I excluded the max line check from utils.py  because the number dictionary is too long.

**Checklist**
Done? Check if you have it all in place using this list:*
  
- [ ] Describes changes in the format above (present tense)
- [ ] Links to an existing issue or discussion 
- [ ] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by jpelay** [comment]
I'm already done with all of the files!

**Comment by mennoliefstingh** [comment]
Great work! I did a scan of a few files and didn't see any weird things. Tests pass too so I'm inclined to approve this PR, but would like to get @TiBiBa in on it if possible first.

**Review by TiBiBa — CHANGES_REQUESTED** [review]
All looks good to me! One minor related change: can we add `pre-commit` to `requirements.txt`?

**Comment by jpelay** [comment]
> All looks good to me! One minor related change: can we add `pre-commit` to `requirements.txt`? On the long run I would also like to add some bash script that handles all the setup for the contributor as it is getting a bit complex for a new contributor to get started with Hedy. But, this seems best for a separate issue to solve.

I agree with you! I did add it to requirements.txt, however the user still has to manually run: `pre-commit install` due to the various reason listed by pre-commit author here: https://stackoverflow.com/questions/71086922/install-pre-commit-on-package-install-in-setup-py-file

**Comment by TiBiBa** [comment]
> > All looks good to me! One minor related change: can we add `pre-commit` to `requirements.txt`? On the long run I would also like to add some bash script that handles all the setup for the contributor as it is getting a bit complex for a new contributor to get started with Hedy. But, this seems best for a separate issue to solve.
> 
> I agree with you! I did add it to requirements.txt, however the user still has to manually run: `pre-commit install` due to the various reason listed by pre-commit author here: https://stackoverflow.com/questions/71086922/install-pre-commit-on-package-install-in-setup-py-file

I see! But we would still be able to run this using a bash script, I can look into this.

**Review by TiBiBa — APPROVED** [review]
This is fine by me once the merge conflicts are fixed!

**Pull request merged**
