### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Hedy/Adventures](https://hosted.weblate.org/projects/hedy/adventures/).

It also includes following components:

* [Hedy/client-messages](https://hosted.weblate.org/projects/hedy/client-messages/)

* [Hedy/Parsons](https://hosted.weblate.org/projects/hedy/parsons/)

* [Hedy/Achievements](https://hosted.weblate.org/projects/hedy/achievements/)

* [Hedy/slides](https://hosted.weblate.org/projects/hedy/slides/)

* [Hedy/Webpages](https://hosted.weblate.org/projects/hedy/webpages/)

* [Hedy/Keywords](https://hosted.weblate.org/projects/hedy/keywords/)

* [Hedy/Cheatsheets](https://hosted.weblate.org/projects/hedy/commands/)

* [Hedy/Quizzes](https://hosted.weblate.org/projects/hedy/quizzes/)

* [Hedy/Texts](https://hosted.weblate.org/projects/hedy/web-texts/)

* [Hedy/Tutorials](https://hosted.weblate.org/projects/hedy/tutorials/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by yilmazdurmaz** [comment]
It seems there is a fight going on between the sorting script and Weblate over two things:

- length of strings on a single line:
  - script has 300 char max length
  - Weblate puts it all back in a single line, the script splits them again

- number of spaces at the beginning (indentation)
  - script has 4 spaces for the indentation
  - Weblate changes this to 2 spaces on commits, script puts back to 4 spaces

These two things happen on every commit and add unnecessary complexity to the commit history.

Are there any settings for this on Weblate to fix the problem there?

**Comment by Felienne** [comment]
> It seems there is a fight going on between the sorting script and Weblate over two things:
> 
> * length of strings on a single line:
>   
>   * script has 300 char max length
>   * Weblate puts it all back in a single line, the script splits them again
> * number of spaces at the beginning (indentation)
>   
>   * script has 4 spaces for the indentation
>   * Weblate changes this to 2 spaces on commits, script puts back to 4 spaces

Thanks for noticing, I updated a change in Weblate causing this, I reverted it for now.

> These two things happen on every commit and add unnecessary complexity to the commit history.
 
> Are there any settings for this on Weblate to fix the problem there?

The problem is reversed, I would prefer it to be fixes in the autoformatter, since otherwise we will run into other problems, I will look into the details tomorrow.

**Comment by Felienne** [comment]
Ah never mind, it was not my setting, but the yaml-sorter. I will disable it for now until we know how to output yamls that make Weblate happy.

**Comment by yilmazdurmaz** [comment]
It has been over 3 hours. Does Weblate have a direct check on the source? If so, how often?
otherwise, I think your tests will need Weblate lock and manual push.

Please note that because of the issues with this PR, alpha-hedy has not got updated translations for the last few days. I hope you don't accidentally release the current alpha to production as at least Turkish frontpage translations are broken for the moment. May not be hard to revert, but would be annoying for sure.

**Comment by Felienne** [comment]
> It has been over 3 hours. Does Weblate have a direct check on the source? 

Yes it seems indeed that Weblate does not push upon changes. Your diagnosis of yesterday (while I know it was meant well) might have been counterproductive because it send me thinking the wrong direction.

> Please note that because of the issues with this PR, alpha-hedy has not got updated translations for the last few days. 

I really understand your eagerness to get everything out, but we simply cannot keep tabs on all the individual changes to languages, inevitable sometimes stuff is in an incorrect or inconsistent state. Again, I would like to ask you to understand we are all doing our best here, and that we do the best we can.

**Comment by yilmazdurmaz** [comment]
> Your diagnosis of yesterday (while I know it was meant well) might have been counterproductive because it send me thinking the wrong direction

Thanks for the warning. I am really sorry about that. I thought that way because, after you pushed changes to Weblate last time, it seemed to revert internally on its database and then commit so, and then sorter was trying to change them again.

**Comment by yilmazdurmaz** [comment]
To clarify what I was seeing back when sorter script was running, here are two sample files diffs from latest commit here:

This file has the change I mentioned for spaces; `|4` to `|2`. the sorter tries to change it back to `|4`
https://github.com/hedyorg/hedy/compare/b79c09ce3d265f53c5ecd956143c9bb5bf2b7f28..d51bda4ba544e534e3f3d700ce747af21220a991#diff-5f48cc3ef59036fa018a59a45027dd9c5ad811bd24ac7c5ca9daa6ef44313aee

This file has the change I mentioned for line length; Weblate converts them to a single line, script splits it again to max 300 char per line.
https://github.com/hedyorg/hedy/compare/b79c09ce3d265f53c5ecd956143c9bb5bf2b7f28..d51bda4ba544e534e3f3d700ce747af21220a991#diff-92289a32efb8c8cbc4dbb0ed43cf551e7770d099503af2db1b11d27fba9f026b

**Comment by yilmazdurmaz** [comment]
After you pushed changes from sorter, on Weblate, I made small changes on each component for Turkish and reverted them at the same time so it would push any and only changes made by Weblate itself. I forgot to check but these will also (most possibly) be changed by the sorter and the loop will continue.

There are also two *kinda* reverse situation:

Here, Weblate adds spaces to extend items to 4 characters away from start (content/client-messages/tr.yaml):
https://github.com/hedyorg/hedy/compare/b79c09ce3d265f53c5ecd956143c9bb5bf2b7f28..d51bda4ba544e534e3f3d700ce747af21220a991#diff-6ef117e20e2cb2f76703270e98995a02253e13f7d556ec650eaadd8ab47335f3

Here, Weblate splits strings at about 90 characters adding extra lines (content/tutorials/tr.yaml):
https://github.com/hedyorg/hedy/compare/b79c09ce3d265f53c5ecd956143c9bb5bf2b7f28..d51bda4ba544e534e3f3d700ce747af21220a991#diff-21afe50b384f1cb28e3d9a00f784bf7da70097e12fb9d80340af0a71d66d2b83

I made these observations so you would spend less time to see them.

Please have a look only when you got enough time.

**Comment by Felienne** [comment]
> > Your diagnosis of yesterday (while I know it was meant well) might have been counterproductive because it send me thinking the wrong direction
> 
> Thanks for the warning. I am really sorry about that. I thought that way because, after you pushed changes to Weblate last time, it seemed to revert internally on its database and then commit so, and then sorter was trying to change them again.

Yes it makes sense that you thought that way because it did very much look like a stand off!

**Review by Felienne — APPROVED** [review]
well that autofix was really helpful!

**Pull request merged**
