### PR TITLE
[BUG FIX] Fix embedded editor when in read only mode

### PR DESCRIPTION
**Pull request by TiBiBa**
This PR fixes a bug where there would be whitespace add the bottom of the embedded editor when on readonly and disabled run mode. This because we calculated the height of the editor based on the height of the run button. But if it's not there, no need to take this space!

The following test link should no longer have whitespace at the bottom:
http://127.0.0.1:8080/embedded/1/?lang=nl&run=false&readOnly=true&program=cHJpbnQgZGl0IGlzIGVlbiB0ZXN0IQplY2hvIHdhYXJvbSBrbG9wdCBkaXQgbmlldD8KdGVzdCB0ZXN0CnRlc3QgdGVzdA%3D%3D

### CODE REVIEW

**Review by jpelay — COMMENTED** [review]
Hi Timon! We totally forgot about trying the read only mode as well! Good catch!

Also, do you think it can be possible to extend the gutter all the way to the bottom? The same way as in the the other editors.
This PR:
image

The main editor:
image

**Comment by TiBiBa** [comment]
> Hi Timon! We totally forgot about trying the read only mode as well! Good catch!
> 
> Also, do you think it can be possible to extend the gutter all the way to the bottom? The same way as in the the other editors. This PR: image
> 
> The main editor: image

I'm unable to re-produce this issue. See the following screenshot:
Scherm­afbeelding 2024-01-04 om 16 45 31

Do you have any clue what might cause this? The editor is already set to full height, I assume CodeMirror handles the gutter height?

**Comment by jpelay** [comment]
> > Hi Timon! We totally forgot about trying the read only mode as well! Good catch!
> > Also, do you think it can be possible to extend the gutter all the way to the bottom? The same way as in the the other editors. This PR: image
> > The main editor: image
> 
> I'm unable to re-produce this issue. See the following screenshot: Scherm­afbeelding 2024-01-04 om 16 45 31
> 
> Do you have any clue what might cause this? The editor is already set to full height, I assume CodeMirror handles the gutter height?

It works perfectly when you have the run button, but not in the case of read only editors, try the link you put in the How to test section.

> I assume CodeMirror handles the gutter height?

You have to set the minimum-height of the parent I think, otherwise it just takes up to the maximum line.

**Review by jpelay — APPROVED** [review]
Sorry! I didn't generate the tailwind first! It works fine now

**Pull request merged**
