### PR TITLE
[Language] Adding error to catch index out of bounds errors

### LINKED ISSUE #3463: [BUG] Unclear message "list index out of range"
**Describe the bug**
When choosing an item from an empty list, you get the error message "list index out of range".

**Paste the Hedy code & level**
Level 16
fruit = []
f = fruit at random
print f

**Add a screenshot (optional)**
See attached file

**Expected behavior**
The message should be more descriptive (and in Dutch) so students will understand it.

image

### PR DESCRIPTION
**Pull request by jpelay**
**Description**

Adds an exception to the code generated after transpiling to catch index out of bounds errors.
Things to do:
- [x] Figure out a way to make the message translatable (`gettext` works inside hedy.py!)
- [x] Try to show which line and variable caused the error. (Can show the variable, not the line!)

**Fixes #3463**

**How to test**

Since this is added **after** transpiling, should I add an e2e test?

**Checklist**
Done? Check if you have it all in place using this list:*
  
- [ ] Contains one of the PR categories in the name
- [ ] Describes changes in the format above
- [ ] Links to an existing issue or discussion 
- [ ] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by jpelay** [comment]
Changed the approach to add exceptions individually before commands that use lists. I think it's better!

image

**Comment by jpelay** [comment]
So this is technically ready, but I have to update 71 tests!

image

**Comment by Felienne** [comment]
Ah sorry I missed this in between all Cypress tests, sorry! Will take a look now.

**Review by Felienne — APPROVED** [review]
Great improvement @jpelay!!

image

**Pull request merged**
