### PR TITLE
[UI] Remove tabs in developer mode

### LINKED ISSUE #4719: [UI idea] remove tabs when in programmer's mode
The adventure tabs don't really make sense in programmer's mode?

**Idea**
image

Steps to fix this would be to change the template to show the tabs only when we are not in programmer's mode.

### PR DESCRIPTION
**Pull request by Annelein**
Fixes #4719

### CODE REVIEW

**Comment by hasan-sh** [comment]
also, @Felienne shouldn't we make this persistent; e.g., same mode after refreshing the page?

**Comment by jpelay** [comment]
> also, @Felienne shouldn't we make this persistent; e.g., same mode after refreshing the page?

We can store it in localStorage for it I think.

**Comment by Felienne** [comment]
> See #4719

Hi @Annelein! Tip: If you writes "fixes" instead of "See" Github will close the issue automatically when we merge the PR. :)

**Comment by Annelein** [comment]
> > also, @Felienne shouldn't we make this persistent; e.g., same mode after refreshing the page?
> 
> We can store it in localStorage for it I think.

How do I access that in Hyperscript?

**Comment by jpelay** [comment]
> How do I access that in Hyperscript? @jpelay @hasan-sh

Seems like you figure it out!

**Pull request closed without merging**
