### PR TITLE
📜 rename the teacher manual section in the yaml files #4701

### PR DESCRIPTION
**Pull request by rmagedon97**
Fixes issue #4701 

**How to test**

Follow these steps to verify this PR works as intended:

I have changed the KEY "section" to teachers-manual" in all. YAML files, which are in content/pages/.yaml.
This should just provide a better naming for the KEY. The change is internal, and it should not affect the website.
To verify everything is working, navigate with a teacher account to the teacher manual. If there is text, it all works.

**Checklist**
Done? Check if you have it all in place using this list: (mark with x if done.)

- [x] Contains one of the PR categories in the name
- [x] Describes changes in the format above
- [x] Links to an existing issue or discussion
- [x] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Review by Felienne — CHANGES_REQUESTED** [review]
Hi @rmagedon97!

The change seems to work well, thanks!!!

However, you seem to also change the order of the sections, start-sections used to come after teacher-guide/sections but now comes before. Is that intentional?

It is not a problem, but it makes it a lot harder to see the changes that you did, so I would prefer it if you can revert that order change

**Comment by Felienne** [comment]
To continue my note above, if I look at the changes now, it shows this:

image

Which is not really the important part of the change.

**Comment by rmagedon97** [comment]
Hello @Felienne, Thank you for your comments.
I think I have filled in all that was missing in the description.

About the sections, because I couldn't fix the issue from the first try, the pre-commit hook did an auto-fix, which changed their order. This should have also been fixed now.

Let me know if I'm missing something else.

**Comment by Felienne** [comment]
Ah, my bad, the order was changed by the rewriter not by you! I should have know this, sorry!

**Review by Felienne — APPROVED** [review]
All good @rmagedon97! Congrats on getting your first PR approved!!

**Pull request merged**
