### PR TITLE
[CONTENT] fixes some typos in pages

### PR DESCRIPTION
**Pull request by Felienne**
I noticed some issues in the pages, but of course this is a weblate lock!

### CODE REVIEW

**Comment by yilmazdurmaz** [comment]
@Felienne with this PR, I saw a worrying problem with Weblate: changes made here are not marked to be "needs editing".

I was thinking I got 100% but the Turkish file you edited showed me I have at least 1 incorrect translation because of this missing notification.

Can you please check if Weblate has a setting to mark changes from repository for further editing?

**Comment by Felienne** [comment]
> @Felienne with this PR, I saw a worrying problem with Weblate: changes made here are not marked to be "needs editing".

Ah good to know!

> I was thinking I got 100% but the Turkish file you edited showed me I have at least 1 incorrect translation because of this missing notification.

Ah, sorry! In the project speed and size as we have it now, sadly, we sometimes do need fixes made outside of Weblate.

> Can you please check if Weblate has a setting to mark changes from repository for further editing?

This is a question for @Mark-Giesen:

Can we mark strings that are changed from a non-Webalte PR as needs editing?

**Comment by yilmazdurmaz** [comment]
> Ah, sorry! In the project speed and size as we have it now, sadly, we sometimes do need fixes made outside of Weblate.

That's absolutely fine as the content continues to evolve. If we can solve this "needs editing" problem, then it will be of greater help to correcting and synching towards other languages.

**Comment by Felienne** [comment]
> > Ah, sorry! In the project speed and size as we have it now, sadly, we sometimes do need fixes made outside of Weblate.
> 
> That's absolutely fine as the content continues to evolve. If we can solve this "needs editing" problem, then it will be of greater help to correcting and synching towards other languages.

yes let's see if Mark knows a solution!

**Comment by Mark-Giesen** [comment]
> Can we mark strings that are changed from a non-Weblate PR as needs editing?

Yes we can and we do. I've been editing "Needs editing" strings in Dutch this week, usually because of small changes in the source. In these cases Weblates shows both the old en new source strings and highlights the diffs, so the translator sees what changes have been made. This "change detection" is done by Weblate itself if possible, the keys of YAML files are known and if the text changes, it is marked for edit in all other languages. 
In PO files this is done by the pybabel tool during extract or update phase, changed strings are marked as fuzzy and this mark is use by Weblate as trigger to mark the string for edit.
If our translation process is followed these changes should be updated nicely. The only faulty route I can think of is if someone translates right into PO files without setting the fuzzy flag. This way Weblate can't see if this is a new string or an altered one.

**Comment by Mark-Giesen** [comment]
Weblate is a little smarter than you gave it credit for. In the Turkish translation, the change in English is correctly overwritten. You only had one line translated out of the complete text. Weblate noticed the original EN part and patched the change. The problem here seems to be the translation was not finished yet, while someone clicked "save and continue".  In Dutch, Weblate couldn't do this, because that specific line was allready translated. 

How smart these partial updates are in Weblate I don't know.

**Comment by yilmazdurmaz** [comment]
> Weblate noticed the original EN part and patched the change

actually, (sorry for bad news) this was not Weblate. Felienne manually made those corrections in all language files within this PR (unless I missed something)

**Comment by yilmazdurmaz** [comment]
new observation: the history of this string for Dutch on the link above, there is no record of editing through Weblate as you supply the translation here within the repo. yet it has "need editing" mark unlike the Turkish version which saw no editing since my last one except pushes from repo.

of course, I might be wrong so heads up, but it is wise to first check settings for languages. start comparing Dutch and Turkish. 

PS: I am preparing to run a local Weblate instance. If I get success, I may pinpoint such problems (if any). Until then, please bear with me.

**Comment by Mark-Giesen** [comment]
Maybe we're talking about different things? I think Felienne changed "costumizing" into "customizing" in the Englisch version. Your Turkish version now has this change as well, it has "customizing" correctly in the last sentence. So there was no need for "Need editing" to be set, the change was applied.
In the Dutch version, this was not possible because the old "costumizing" was allready translated.

**Comment by yilmazdurmaz** [comment]
> Maybe we're talking about different things?

I think we are just looking at the problem in different angles and our views differ a bit :)

let me add another thing that might have caused Dutch version to have the "needs editing" mark.

screenshot-hosted weblate org-2023 10 18-22_59_43

"I think" this is what happened back then: 3 weeks ago, this string has changed to this new long version, and Dutch component was already translated in the repo. When uploaded to Weblate, it did not like the problems you see in the image and automatically marked it for editing. On the other hand, Turkish version did not have these problems, passed the checks, and never marked.

If this is true, then there was (and is) no settings to make the mark in the first place. I don't know, however, how to test this possibility.

**Comment by yilmazdurmaz** [comment]
oh, by the way, the whole string actually "needs" to be edited as it is "not" really translated after it was added 3 weeks ago, and I was not aware of it since then, until I see this PR, because of this marking issue.

**Comment by Mark-Giesen** [comment]
To test if it works, you can change a string in English in Weblate, all languages with translations should have the "need editing" set after that (can take en few minutes). If that works, you could try the same with an string in the yaml file in our repo. I did something with a test_string last week, you could try something like that. Tests take some time though.

**Comment by yilmazdurmaz** [comment]
> you can change a string in English in Weblate

There is no problem with changing within Weblate. I made a lot of small changes like that and it marks them fine. The problem, I think, is with the changes directly pushed from here.

for changing a yaml file here, "why not". for the moment, my brain is in a bit of lazy night mod for such a trial, so it may take a few hours to decide a workflow. but basically, these two are the things on mind:
- select an English string that needs a small typo such as backticks, and make edit here on a yaml file
- select a Turkish string that already needs a bit of touch, and make edit here on a yaml file
- push the two files and see what Weblate's response is.

I will ping you in it when I make that PR

**Pull request merged**
