### PR TITLE
[CHORE, TESTING] pretty print exception output for better readability

### LINKED ISSUE #3582: [CHORE, TESTING] Improve error output
Feedback "false is not true" is not really helpful: 

image

(This is a note to self, no help needed atm!)

### PR DESCRIPTION
**Pull request by Felienne**
Fixes #3582 and will also be helpful if we ever present this to translators.

**How to test**
Deliberately destroy a code snippet in one of the snippet folders (f.e. remove a closing bracket, or misspel a keyword) and verify you get better output that `False is not True`

### CODE REVIEW

**Comment by jpelay** [comment]
Miss Felienne, all of the snippets tests are failing locally without changing anything, just by running them. All of them basically say the same thing:

```
-------TestsParsonsPrograms.test_parsons_75_fr_8_1 -------

a = (<test_parsons.TestsParsonsPrograms testMethod=test_parsons_75_fr_8_1>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

/home/capybara/repos/hedyc/.env/lib/python3.8/site-packages/parameterized/parameterized.py:533: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/capybara/repos/hedyc/tests/test_snippets/test_parsons.py:62: in test_parsons
    self.assertTrue(result)
E   AssertionError: None is not true
--------Captured stdout call----------------
teams = red, yellow, blue
affiche 'Rouge, Jaune ou Bleu ?'
répète 5 fois
  affiche 'You are selected in team... '
  affiche teams au hasard
  sleep 2

```

**Comment by Felienne** [comment]
That is so weird, since the tests pass on Github!

**Comment by Felienne** [comment]
Ow haha, I get it! The tests did not fully run because of the optimization PR! I found the issue, will update!

**Comment by Felienne** [comment]
Good thing you are checking my PRs!!

**Comment by jpelay** [comment]
It's working now!

**Review by jpelay — APPROVED** [review]

**Pull request merged**
